"""미국 자동 확장 유니버스 — 나스닥+NYSE+AMEX 전 섹터.
생성일: 2026-07-02 | 출처: rreichel3/US-Stock-Symbols (github)
필터: 주가 $10+ · 시총 $500M+ · 거래량 30만주+ · ETF/펀드/워런트/우선주 제외.
(v4.48.1: 성장섹터 한정 해제 — 산업재 등 전 섹터 포함, 1292→2072개)
거래대금 동적 필터(scanner)로 실제 스캔 시 저거래 종목은 추가 제외됨."""

US_UNIVERSE_AUTO = {
    "A": "Agilent Technologies Inc.",    "AA": "Alcoa Corporation",    "AADX": "Applied Aerospace & Defense Inc.",    "AAL": "American Airlines Group Inc.",
    "AAMI": "Acadian Asset Management Inc.",    "AAOI": "Applied Optoelectronics Inc.",    "AAON": "AAON Inc.",    "AAP": "Advance Auto Parts Inc.",
    "AAPL": "Apple Inc.",    "ABBV": "AbbVie Inc.",    "ABCB": "Ameris Bancorp",    "ABM": "ABM Industries Incorporated",
    "ABNB": "Airbnb Inc.",    "ABSI": "Absci Corporation",    "ABT": "Abbott Laboratories",    "ABX": "Abacus Global Management Inc.",
    "ACA": "Arcosa Inc.",    "ACAD": "ACADIA Pharmaceuticals Inc.",    "ACGL": "Arch Capital Group Ltd.",    "ACHC": "Acadia Healthcare Company Inc.",
    "ACI": "Albertsons Companies Inc.",    "ACIW": "ACI Worldwide Inc.",    "ACLS": "Axcelis Technologies Inc.",    "ACM": "AECOM",
    "ACMR": "ACM Research Inc.",    "ACN": "Accenture plc",    "ACT": "Enact Holdings Inc.",    "AD": "Array Digital Infrastructure Inc. Common",
    "ADBE": "Adobe Inc.",    "ADC": "Agree Realty Corporation",    "ADEA": "Adeia Inc.",    "ADI": "Analog Devices Inc.",
    "ADM": "Archer-Daniels-Midland Company",    "ADNT": "Adient plc",    "ADP": "Automatic Data Processing Inc.",    "ADPT": "Adaptive Biotechnologies Corporation",
    "ADSK": "Autodesk Inc.",    "ADTN": "ADTRAN Holdings Inc.",    "ADUR": "Aduro Clean Technologies Inc.",    "AEE": "Ameren Corporation",
    "AEHR": "Aehr Test Systems",    "AEIS": "Advanced Energy Industries Inc.",    "AEM": "Agnico Eagle Mines Limited",    "AEO": "American Eagle Outfitters Inc.",
    "AEP": "American Electric Power Company Inc.",    "AER": "AerCap Holdings N.V.",    "AES": "The AES Corporation",    "AESI": "Atlas Energy Solutions Inc.",
    "AEVA": "Aeva Technologies Inc.",    "AFG": "American Financial Group Inc.",    "AFL": "AFLAC Incorporated",    "AFRM": "Affirm Holdings Inc.",
    "AG": "First Majestic Silver Corp.",    "AGCO": "AGCO Corporation",    "AGI": "Alamos Gold Inc.",    "AGIO": "Agios Pharmaceuticals Inc.",
    "AGL": "agilon health inc.",    "AGNC": "AGNC Investment Corp.",    "AGO": "Assured Guaranty Ltd.",    "AHCO": "AdaptHealth Corp.",
    "AHR": "American Healthcare REIT Inc.",    "AIG": "American International Group Inc. New",    "AIP": "Arteris Inc.",    "AIR": "AAR Corp.",
    "AIZ": "Assurant Inc.",    "AJG": "Arthur J. Gallagher & Co.",    "AKAM": "Akamai Technologies Inc.",    "AKTS": "Aktis Oncology Inc. Common stock",
    "ALAB": "Astera Labs Inc.",    "ALB": "Albemarle Corporation",    "ALC": "Alcon Inc.",    "ALGM": "Allegro MicroSystems Inc.",
    "ALGN": "Align Technology Inc.",    "ALGT": "Allegiant Travel Company",    "ALH": "Alliance Laundry Holdings Inc.",    "ALHC": "Alignment Healthcare Inc.",
    "ALIT": "Alight Inc.",    "ALK": "Alaska Air Group Inc.",    "ALKS": "Alkermes plc",    "ALKT": "Alkami Technology Inc.",
    "ALL": "Allstate Corporation (The)",    "ALLE": "Allegion plc",    "ALLY": "Ally Financial Inc.",    "ALM": "Almonty Industries Inc. Common Shares",
    "ALMR": "Alamar Biosciences Inc.",    "ALMS": "Alumis Inc.",    "ALNY": "Alnylam Pharmaceuticals Inc.",    "ALOY": "REalloys Inc.",
    "ALRM": "Alarm.com Holdings Inc.",    "ALSN": "Allison Transmission Holdings Inc.",    "ALV": "Autoliv Inc.",    "AM": "Antero Midstream Corporation",
    "AMAT": "Applied Materials Inc.",    "AMBA": "Ambarella Inc.",    "AMBQ": "Ambiq Micro Inc.",    "AMCR": "Amcor plc",
    "AMD": "Advanced Micro Devices Inc.",    "AME": "AMETEK Inc.",    "AMG": "Affiliated Managers Group Inc.",    "AMGN": "Amgen Inc.",
    "AMH": "American Homes 4 Rent Common Shares of B",    "AMKR": "Amkor Technology Inc.",    "AMLX": "Amylyx Pharmaceuticals Inc.",    "AMN": "AMN Healthcare Services Inc",
    "AMP": "Ameriprise Financial Inc.",    "AMPH": "Amphastar Pharmaceuticals Inc.",    "AMPX": "Amprius Technologies Inc.",    "AMRC": "Ameresco Inc.",
    "AMRX": "Amneal Pharmaceuticals Inc.",    "AMRZ": "Amrize Ltd",    "AMSC": "American Superconductor Corporation",    "AMT": "American Tower Corporation (REIT)",
    "AMTM": "Amentum Holdings Inc.",    "AMZN": "Amazon.com Inc.",    "AN": "AutoNation Inc.",    "ANAB": "AnaptysBio Inc.",
    "ANDG": "Andersen Group Inc.",    "ANET": "Arista Networks Inc.",    "ANF": "Abercrombie & Fitch Company",    "ANGO": "AngioDynamics Inc.",
    "ANRO": "Alto Neuroscience Inc.",    "AON": "Aon plc",    "AORT": "Artivion Inc.",    "AOS": "A.O. Smith Corporation",
    "AOSL": "Alpha and Omega Semiconductor Limited Co",    "APA": "APA Corporation",    "APAM": "Artisan Partners Asset Management Inc.",    "APD": "Air Products and Chemicals Inc.",
    "APG": "APi Group Corporation",    "APGE": "Apogee Therapeutics Inc.",    "APH": "Amphenol Corporation",    "APLD": "Applied Digital Corporation",
    "APLE": "Apple Hospitality REIT Inc. Common Share",    "APO": "Apollo Global Management Inc. (New)",    "APP": "Applovin Corporation",    "APPF": "AppFolio Inc.",
    "APPN": "Appian Corporation",    "APPS": "Digital Turbine Inc.",    "APTV": "Aptiv PLC",    "AR": "Antero Resources Corporation",
    "ARCB": "ArcBest Corporation",    "ARCC": "Ares Capital Corporation",    "ARDT": "Ardent Health Inc.",    "ARE": "Alexandria Real Estate Equities Inc.",
    "ARES": "Ares Management Corporation",    "ARI": "Apollo Commercial Real Estate Finance In",    "ARIS": "Aris Mining Corporation Common Shares",    "ARLO": "Arlo Technologies Inc.",
    "ARMK": "Aramark",    "AROC": "Archrock Inc.",    "ARQQ": "Arqit Quantum Inc.",    "ARQT": "Arcutis Biotherapeutics Inc.",
    "ARR": "ARMOUR Residential REIT Inc.",    "ARW": "Arrow Electronics Inc.",    "ARWR": "Arrowhead Pharmaceuticals Inc.",    "ARX": "Accelerant Holdings",
    "ARXS": "Arxis Inc.",    "AS": "Amer Sports Inc.",    "ASB": "Associated Banc-Corp",    "ASC": "Ardmore Shipping Corporation",
    "ASH": "Ashland Inc.",    "ASML": "ASML Holding N.V. New York Registry Shar",    "ASND": "Ascendis Pharma A/S Ordinary Share",    "ASO": "Academy Sports and Outdoors Inc.",
    "ASST": "Strive Inc.",    "ASTH": "Astrana Health Inc.",    "ASTS": "AST SpaceMobile Inc.",    "ATEN": "A10 Networks Inc.",
    "ATEX": "Anterix Inc.",    "ATI": "ATI Inc.",    "ATMU": "Atmus Filtration Technologies Inc.",    "ATO": "Atmos Energy Corporation",
    "ATR": "AptarGroup Inc.",    "ATRC": "AtriCure Inc.",    "ATRO": "Astronics Corporation",    "AU": "AngloGold Ashanti PLC",
    "AUB": "Atlantic Union Bankshares Corporation",    "AUGO": "Aura Minerals Inc. Common Shares",    "AUPH": "Aurinia Pharmaceuticals Inc",    "AVA": "Avista Corporation",
    "AVAV": "AeroVironment Inc.",    "AVB": "AvalonBay Communities Inc.",    "AVBP": "ArriVent BioPharma Inc.",    "AVEX": "AEVEX Corp.",
    "AVGO": "Broadcom Inc.",    "AVLN": "Avalyn Pharma Inc.",    "AVNS": "Avanos Medical Inc.",    "AVNT": "Avient Corporation",
    "AVO": "Mission Produce Inc.",    "AVPT": "AvePoint Inc.",    "AVT": "Avnet Inc.",    "AVTR": "Avantor Inc.",
    "AVTX": "Avalo Therapeutics Inc.",    "AVY": "Avery Dennison Corporation",    "AWI": "Armstrong World Industries Inc",    "AWK": "American Water Works Company Inc.",
    "AWR": "American States Water Company",    "AX": "Axos Financial Inc.",    "AXGN": "Axogen Inc.",    "AXON": "Axon Enterprise Inc.",
    "AXP": "American Express Company",    "AXS": "Axis Capital Holdings Limited",    "AXSM": "Axsome Therapeutics Inc.",    "AXTA": "Axalta Coating Systems Ltd. Common Share",
    "AXTI": "AXT Inc",    "AYI": "Acuity Inc.",    "AZN": "AstraZeneca PLC",    "AZO": "AutoZone Inc.",
    "AZTA": "Azenta Inc.",    "AZZ": "AZZ Inc.",    "B": "Barrick Mining Corporation Common Shares",    "BA": "Boeing Company (The)",
    "BAC": "Bank of America Corporation",    "BAH": "Booz Allen Hamilton Holding Corporation",    "BALL": "Ball Corporation",    "BAM": "Brookfield Asset Management Inc",
    "BANC": "Banc of California Inc.",    "BAND": "Bandwidth Inc.",    "BAP": "Credicorp Ltd.",    "BATRK": "Atlanta Braves Holdings Inc. Series C",
    "BAX": "Baxter International Inc.",    "BB": "BlackBerry Limited",    "BBAR": "Banco BBVA Argentina S.A. ADS",    "BBIO": "BridgeBio Pharma Inc.",
    "BBNX": "Beta Bionics Inc.",    "BBT": "Beacon Financial Corporation Common stoc",    "BBUC": "Brookfield Business Corporation",    "BBVA": "Banco Bilbao Vizcaya Argentaria S.A.",
    "BBWI": "Bath & Body Works Inc.",    "BBY": "Best Buy Co. Inc.",    "BC": "Brunswick Corporation",    "BCAX": "Bicara Therapeutics Inc.",
    "BCC": "Boise Cascade L.L.C.",    "BCE": "BCE Inc.",    "BCO": "Brinks Company (The)",    "BCS": "Barclays PLC",
    "BDC": "Belden Inc",    "BDX": "Becton Dickinson and Company",    "BE": "Bloom Energy Corporation",    "BEAM": "Beam Therapeutics Inc.",
    "BELFA": "Bel Fuse Inc.",    "BELFB": "Bel Fuse Inc.",    "BEN": "Franklin Resources Inc.",    "BEPC": "Brookfield Renewable Corporation Brookfi",
    "BETA": "Beta Technologies Inc.",    "BETR": "Better Home & Finance Holding Company",    "BFAM": "Bright Horizons Family Solutions Inc.",    "BFH": "Bread Financial Holdings Inc.",
    "BG": "Bunge Limited Common Shares",    "BGC": "BGC Group Inc.",    "BHE": "Benchmark Electronics Inc.",    "BHF": "Brighthouse Financial Inc.",
    "BHVN": "Biohaven Ltd. Common Shares",    "BIDU": "Baidu Inc. ADS",    "BIIB": "Biogen Inc.",    "BILL": "BILL Holdings Inc.",
    "BIOA": "BioAge Labs Inc.",    "BIPC": "Brookfield Infrastructure Corporation Br",    "BIRK": "Birkenstock Holding plc",    "BJ": "BJ's Wholesale Club Holdings Inc.",
    "BJRI": "BJ's Restaurants Inc.",    "BKD": "Brookdale Senior Living Inc.",    "BKE": "Buckle Inc. (The)",    "BKH": "Black Hills Corporation",
    "BKNG": "Booking Holdings Inc.",    "BKR": "Baker Hughes Company",    "BKSY": "BlackSky Technology Inc.",    "BKU": "BankUnited Inc.",
    "BKV": "BKV Corporation",    "BL": "BlackLine Inc.",    "BLBD": "Blue Bird Corporation",    "BLCO": "Bausch + Lomb Corporation Common Shares",
    "BLDR": "Builders FirstSource Inc.",    "BLFS": "BioLife Solutions Inc.",    "BLK": "BlackRock Inc.",    "BLKB": "Blackbaud Inc.",
    "BLLN": "BillionToOne Inc.",    "BLSH": "Bullish",    "BLZE": "Backblaze Inc.",    "BMI": "Badger Meter Inc.",
    "BMNR": "BitMine Immersion Technologies Inc.",    "BMRN": "BioMarin Pharmaceutical Inc.",    "BMY": "Bristol-Myers Squibb Company",    "BN": "Brookfield Corporation",
    "BNL": "Broadstone Net Lease Inc.",    "BNS": "Bank Nova Scotia Halifax Pfd 3",    "BNY": "The Bank of New York Mellon Corporation",    "BOBS": "Bob's Discount Furniture Inc.",
    "BOH": "Bank of Hawaii Corporation",    "BOOT": "Boot Barn Holdings Inc.",    "BOX": "Box Inc.",    "BP": "BP p.l.c.",
    "BPOP": "Popular Inc.",    "BR": "Broadridge Financial Solutions Inc.",    "BRBR": "BellRing Brands Inc.",    "BRKR": "Bruker Corporation",
    "BRO": "Brown & Brown Inc.",    "BROS": "Dutch Bros Inc.",    "BRSL": "Brightstar Lottery PLC Trading under the",    "BRUN": "Boost Run Inc.",
    "BRX": "Brixmor Property Group Inc.",    "BRZE": "Braze Inc.",    "BSX": "Boston Scientific Corporation",    "BSY": "Bentley Systems Incorporated",
    "BTDR": "Bitdeer Technologies Group",    "BTI": "British American Tobacco  Industries p.l",    "BTSG": "BrightSpring Health Services Inc.",    "BTU": "Peabody Energy Corporation",
    "BUD": "Anheuser-Busch Inbev SA Sponsored ADR (B",    "BURL": "Burlington Stores Inc.",    "BUSE": "First Busey Corporation",    "BV": "BrightView Holdings Inc.",
    "BVN": "Buenaventura Mining Company Inc.",    "BW": "Babcock & Wilcox Enterprises Inc.",    "BWA": "BorgWarner Inc.",    "BWIN": "The Baldwin Insurance Group Inc.",
    "BWXT": "BWX Technologies Inc.",    "BX": "Blackstone Inc.",    "BXP": "BXP Inc.",    "BY": "Byline Bancorp Inc.",
    "BYD": "Boyd Gaming Corporation",    "BZ": "KANZHUN LIMITED American Depository Shar",    "BZH": "Beazer Homes USA Inc.",    "C": "Citigroup Inc.",
    "CAE": "CAE Inc.",    "CAG": "ConAgra Brands Inc.",    "CAH": "Cardinal Health Inc.",    "CAI": "Caris Life Sciences Inc.",
    "CAKE": "Cheesecake Factory Incorporated (The)",    "CALM": "Cal-Maine Foods Inc.",    "CALX": "Calix Inc",    "CALY": "Callaway Golf Company",
    "CAMT": "Camtek Ltd.",    "CAPR": "Capricor Therapeutics Inc.",    "CAR": "Avis Budget Group Inc.",    "CARE": "Carter Bankshares Inc.",
    "CARG": "CarGurus Inc.",    "CARR": "Carrier Global Corporation",    "CARS": "Cars.com Inc.",    "CART": "Maplebear Inc.",
    "CASH": "Pathward Financial Inc.",    "CASY": "Casey's General Stores Inc.",    "CAT": "Caterpillar Inc.",    "CATY": "Cathay General Bancorp",
    "CAVA": "CAVA Group Inc.",    "CB": "Chubb Limited",    "CBC": "Central Bancompany Inc.",    "CBL": "CBL & Associates Properties Inc.",
    "CBLL": "CeriBell Inc.",    "CBRE": "CBRE Group Inc Common Stock",    "CBRL": "Cracker Barrel Old Country Store Inc",    "CBRS": "Cerebras Systems Inc.",
    "CBSH": "Commerce Bancshares Inc.",    "CBT": "Cabot Corporation",    "CBZ": "CBIZ Inc.",    "CC": "Chemours Company (The)",
    "CCEP": "Coca-Cola Europacific Partners plc",    "CCI": "Crown Castle Inc.",    "CCJ": "Cameco Corporation",    "CCK": "Crown Holdings Inc.",
    "CCL": "Carnival Corporation Ltd. Common Shares",    "CCOI": "Cogent Communications Holdings Inc.",    "CCS": "Century Communities Inc.",    "CDE": "Coeur Mining Inc.",
    "CDNA": "CareDx Inc.",    "CDNL": "Cardinal Infrastructure Group Inc.",    "CDNS": "Cadence Design Systems Inc.",    "CDP": "COPT Defense Properties Common Shares of",
    "CDW": "CDW Corporation",    "CE": "Celanese Corporation",    "CECO": "CECO Environmental Corp.",    "CEG": "Constellation Energy Corporation",
    "CELC": "Celcuity Inc.",    "CELH": "Celsius Holdings Inc.",    "CENX": "Century Aluminum Company",    "CEVA": "CEVA Inc.",
    "CF": "CF Industries Holdings Inc.",    "CFG": "Citizens Financial Group Inc.",    "CFR": "Cullen/Frost Bankers Inc.",    "CG": "The Carlyle Group Inc.",
    "CGAU": "Centerra Gold Inc. Common Shares",    "CGBD": "Carlyle Secured Lending Inc.",    "CGEM": "Cullinan Therapeutics Inc.",    "CGNX": "Cognex Corporation",
    "CGON": "CG Oncology Inc. Common stock",    "CHD": "Church & Dwight Company Inc.",    "CHDN": "Churchill Downs Incorporated",    "CHEF": "The Chefs' Warehouse Inc.",
    "CHH": "Choice Hotels International Inc.",    "CHKP": "Check Point Software Technologies Ltd.",    "CHRD": "Chord Energy Corporation",    "CHRW": "C.H. Robinson Worldwide Inc.",
    "CHTR": "Charter Communications Inc.",    "CHWY": "Chewy Inc.",    "CHYM": "Chime Financial Inc.",    "CI": "The Cigna Group",
    "CIEN": "Ciena Corporation",    "CIFR": "Cipher Digital Inc.",    "CIM": "Chimera Investment Corporation",    "CINF": "Cincinnati Financial Corporation",
    "CL": "Colgate-Palmolive Company",    "CLB": "Core Laboratories Inc.",    "CLBK": "Columbia Financial Inc.",    "CLBT": "Cellebrite DI Ltd.",
    "CLDX": "Celldex Therapeutics Inc.",    "CLH": "Clean Harbors Inc.",    "CLMT": "Calumet Inc.",    "CLPT": "ClearPoint Neuro Inc.",
    "CLS": "Celestica Inc.",    "CLSK": "CleanSpark Inc.",    "CLX": "Clorox Company (The)",    "CLYM": "Climb Bio Inc.",
    "CM": "Canadian Imperial Bank of Commerce",    "CMBT": "CMB.TECH NV",    "CMC": "Commercial Metals Company",    "CMCSA": "Comcast Corporation",
    "CME": "CME Group Inc.",    "CMG": "Chipotle Mexican Grill Inc.",    "CMI": "Cummins Inc.",    "CMP": "Compass Minerals Intl Inc",
    "CMPS": "COMPASS Pathways Plc American Depository",    "CMRE": "Costamare Inc. Common Stock $0.0001 par ",    "CMS": "CMS Energy Corporation",    "CNA": "CNA Financial Corporation",
    "CNC": "Centene Corporation",    "CNH": "CNH Industrial N.V. Common Shares",    "CNI": "Canadian National Railway Company",    "CNK": "Cinemark Holdings Inc Cinemark Holdings ",
    "CNM": "Core & Main Inc.",    "CNMD": "CONMED Corporation",    "CNNE": "Cannae Holdings Inc.",    "CNO": "CNO Financial Group Inc.",
    "CNOB": "ConnectOne Bancorp Inc.",    "CNP": "CenterPoint Energy Inc (Holding Co)",    "CNQ": "Canadian Natural Resources Limited",    "CNR": "Core Natural Resources Inc.",
    "CNX": "CNX Resources Corporation",    "CNXC": "Concentrix Corporation",    "COCO": "The Vita Coco Company Inc.",    "CODI": "D/B/A Compass Diversified Holdings Share",
    "COF": "Capital One Financial Corporation",    "COGT": "Cogent Biosciences Inc.",    "COHR": "Coherent Corp.",    "COHU": "Cohu Inc.",
    "COIN": "Coinbase Global Inc.",    "COKE": "Coca-Cola Consolidated Inc.",    "COLB": "Columbia Banking System Inc.",    "COLL": "Collegium Pharmaceutical Inc.",
    "COLM": "Columbia Sportswear Company",    "COMP": "Compass Inc.",    "CON": "Concentra Group Holdings Parent Inc.",    "COO": "The Cooper Companies Inc.",
    "COP": "ConocoPhillips",    "COR": "Cencora Inc.",    "CORT": "Corcept Therapeutics Incorporated",    "CORZ": "Core Scientific Inc.",
    "COST": "Costco Wholesale Corporation",    "CP": "Canadian Pacific Kansas City Limited Com",    "CPA": "Copa Holdings S.A.",    "CPAY": "Corpay Inc.",
    "CPB": "The Campbell's Company",    "CPNG": "Coupang Inc.",    "CPRI": "Capri Holdings Limited",    "CPRT": "Copart Inc. (DE)",
    "CPRX": "Catalyst Pharmaceuticals Inc.",    "CR": "Crane Company",    "CRBG": "Corebridge Financial Inc.",    "CRC": "California Resources Corporation",
    "CRCL": "Circle Internet Group Inc.",    "CRDO": "Credo Technology Group Holding Ltd",    "CRH": "CRH PLC",    "CRI": "Carter's Inc.",
    "CRK": "Comstock Resources Inc.",    "CRL": "Charles River Laboratories International",    "CRM": "Salesforce Inc.",    "CRNC": "Cerence Inc.",
    "CRNX": "Crinetics Pharmaceuticals Inc.",    "CROX": "Crocs Inc.",    "CRS": "Carpenter Technology Corporation",    "CRSP": "CRISPR Therapeutics AG Common Shares",
    "CRUS": "Cirrus Logic Inc.",    "CRVS": "Corvus Pharmaceuticals Inc.",    "CRWD": "CrowdStrike Holdings Inc.",    "CRWV": "CoreWeave Inc.",
    "CSCO": "Cisco Systems Inc. Common Stock (DE)",    "CSGP": "CoStar Group Inc.",    "CSIQ": "Canadian Solar Inc. Common Shares (ON)",    "CSL": "Carlisle Companies Incorporated",
    "CSTL": "Castle Biosciences Inc.",    "CSTM": "Constellium SE",    "CSWC": "Capital Southwest Corporation",    "CSX": "CSX Corporation",
    "CTAS": "Cintas Corporation",    "CTNM": "Contineum Therapeutics Inc.",    "CTO": "CTO Realty Growth Inc.",    "CTOS": "Custom Truck One Source Inc.",
    "CTRE": "CareTrust REIT Inc.",    "CTRI": "Centuri Holdings Inc.",    "CTSH": "Cognizant Technology Solutions Corporati",    "CTVA": "Corteva Inc.",
    "CUBE": "CubeSmart Common Shares",    "CUBI": "Customers Bancorp Inc",    "CURB": "Curbline Properties Corp.",    "CUZ": "Cousins Properties Incorporated",
    "CVBF": "CVB Financial Corporation",    "CVE": "Cenovus Energy Inc",    "CVI": "CVR Energy Inc.",    "CVLT": "Commvault Systems Inc.",
    "CVNA": "Carvana Co.",    "CVS": "CVS Health Corporation",    "CVSA": "Covista Inc. Common Shares",    "CVX": "Chevron Corporation",
    "CWBC": "Community West Bancshares",    "CWEN": "Clearway Energy Inc.",    "CWK": "Cushman & Wakefield Ltd. Common Shares",    "CWST": "Casella Waste Systems Inc.",
    "CWT": "California Water Service Group",    "CX": "Cemex S.A.B. de C.V. Sponsored ADR",    "CXT": "Crane NXT Co.",    "CXW": "CoreCivic Inc.",
    "CYRX": "CryoPort Inc.",    "CYTK": "Cytokinetics Incorporated",    "CZR": "Caesars Entertainment Inc.",    "D": "Dominion Energy Inc.",
    "DAKT": "Daktronics Inc.",    "DAL": "Delta Air Lines Inc.",    "DAN": "Dana Incorporated",    "DAR": "Darling Ingredients Inc.",
    "DASH": "DoorDash Inc.",    "DAVE": "Dave Inc.",    "DB": "Deutsche Bank AG",    "DBD": "Diebold Nixdorf Incorporated Common stoc",
    "DBRG": "DigitalBridge Group Inc.",    "DBX": "Dropbox Inc.",    "DCI": "Donaldson Company Inc.",    "DD": "DuPont de Nemours Inc.",
    "DDOG": "Datadog Inc.",    "DE": "Deere & Company",    "DEA": "Easterly Government Properties Inc.",    "DEC": "Diversified Energy Company",
    "DECK": "Deckers Outdoor Corporation",    "DEI": "Douglas Emmett Inc.",    "DELL": "Dell Technologies Inc.",    "DEO": "Diageo plc",
    "DFH": "Dream Finders Homes Inc.",    "DFIN": "Donnelley Financial Solutions Inc.",    "DFTX": "Definium Therapeutics Inc. Common Shares",    "DG": "Dollar General Corporation",
    "DGII": "Digi International Inc.",    "DGX": "Quest Diagnostics Incorporated",    "DHI": "D.R. Horton Inc.",    "DHR": "Danaher Corporation",
    "DHT": "DHT Holdings Inc.",    "DINO": "HF Sinclair Corporation",    "DIOD": "Diodes Incorporated",    "DIS": "Walt Disney Company (The)",
    "DK": "Delek US Holdings Inc.",    "DKNG": "DraftKings Inc.",    "DKS": "Dick's Sporting Goods Inc",    "DLB": "Dolby Laboratories",
    "DLO": "DLocal Limited",    "DLTR": "Dollar Tree Inc.",    "DLX": "Deluxe Corporation",    "DMC": "Del Monte Corporation",
    "DMRA": "Damora Therapeutics Inc.",    "DNA": "Ginkgo Bioworks Holdings Inc.",    "DNLI": "Denali Therapeutics Inc.",    "DNOW": "DNOW Inc.",
    "DNTH": "Dianthus Therapeutics Inc.",    "DOC": "Healthpeak Properties Inc.",    "DOCN": "DigitalOcean Holdings Inc.",    "DOCS": "Doximity Inc.",
    "DOCU": "DocuSign Inc.",    "DOLE": "Dole plc",    "DOV": "Dover Corporation",    "DOW": "Dow Inc.",
    "DOX": "Amdocs Limited",    "DPC": "DPC Holdings PLC",    "DPZ": "Domino's Pizza Inc",    "DRH": "Diamondrock Hospitality Company",
    "DRI": "Darden Restaurants Inc.",    "DRS": "Leonardo DRS Inc.",    "DRTS": "Alpha Tau Medical Ltd.",    "DRUG": "Bright Minds Biosciences Inc.",
    "DRVN": "Driven Brands Holdings Inc.",    "DSGN": "Design Therapeutics Inc.",    "DSGX": "Descartes Systems Group Inc. (The)",    "DT": "Dynatrace Inc.",
    "DTE": "DTE Energy Company",    "DTM": "DT Midstream Inc.",    "DUK": "Duke Energy Corporation (Holding Company",    "DUOL": "Duolingo Inc.",
    "DV": "DoubleVerify Holdings Inc.",    "DVA": "DaVita Inc.",    "DVN": "Devon Energy Corporation",    "DX": "Dynex Capital Inc.",
    "DXCM": "DexCom Inc.",    "DY": "Dycom Industries Inc.",    "DYN": "Dyne Therapeutics Inc.",    "E": "ENI S.p.A.",
    "EA": "Electronic Arts Inc.",    "EAT": "Brinker International Inc.",    "EBAY": "eBay Inc.",    "EBC": "Eastern Bankshares Inc.",
    "ECG": "Everus Construction Group Inc.",    "ECHO": "EchoStar  Corporation",    "ECL": "Ecolab Inc.",    "ECPG": "Encore Capital Group Inc",
    "ECVT": "Ecovyst Inc.",    "ED": "Consolidated Edison Inc.",    "EDU": "New Oriental Education & Technology Grou",    "EEFT": "Euronet Worldwide Inc.",
    "EFC": "Ellington Financial Inc.",    "EFOR": "Everforth Inc.",    "EFX": "Equifax Inc.",    "EG": "Everest Group Ltd.",
    "EGBN": "Eagle Bancorp Inc.",    "EGO": "Eldorado Gold Corporation",    "EGP": "EastGroup Properties Inc.",    "EHC": "Encompass Health Corporation",
    "EIKN": "Eikon Therapeutics Inc.",    "EIX": "Edison International",    "EL": "Estee Lauder Companies Inc. (The)",    "ELAN": "Elanco Animal Health Incorporated",
    "ELE": "Elemental Royalty Corporation",    "ELF": "e.l.f. Beauty Inc.",    "ELMT": "The Elmet Group Co.",    "ELS": "Equity Lifestyle Properties Inc.",
    "ELV": "Elevance Health Inc.",    "ELVN": "Enliven Therapeutics Inc.",    "EMBJ": "Embraer S.A.",    "EME": "EMCOR Group Inc.",
    "EMN": "Eastman Chemical Company",    "EMR": "Emerson Electric Company",    "ENB": "Enbridge Inc",    "ENOV": "Enovis Corporation",
    "ENPH": "Enphase Energy Inc.",    "ENR": "Energizer Holdings Inc.",    "ENS": "EnerSys",    "ENSG": "The Ensign Group Inc.",
    "ENTG": "Entegris Inc.",    "ENVA": "Enova International Inc.",    "EOG": "EOG Resources Inc.",    "EPAC": "Enerpac Tool Group Corp.",
    "EPAM": "EPAM Systems Inc.",    "EPC": "Edgewell Personal Care Company",    "EPD": "Enterprise Products Partners L.P.",    "EPR": "EPR Properties",
    "EQH": "Equitable Holdings Inc.",    "EQIX": "Equinix Inc. Common Stock REIT",    "EQNR": "Equinor ASA",    "EQPT": "EquipmentShare.com Inc",
    "EQR": "Equity Residential Common Shares of Bene",    "EQT": "EQT Corporation",    "ERAS": "Erasca Inc.",    "ERIE": "Erie Indemnity Company",
    "ERO": "Ero Copper Corp. Common Shares",    "EROC": "ERock Inc.",    "EROK": "EagleRock Land LLC",    "ES": "Eversource Energy (D/B/A)",
    "ESAB": "ESAB Corporation",    "ESE": "ESCO Technologies Inc.",    "ESI": "Element Solutions Inc.",    "ESNT": "Essent Group Ltd. Common Shares",
    "ESTA": "Establishment Labs Holdings Inc. Common ",    "ESTC": "Elastic N.V.",    "ETD": "Ethan Allen Interiors Inc.",    "ETN": "Eaton Corporation PLC",
    "ETON": "Eton Pharmaceuticals Inc.",    "ETOR": "eToro Group Ltd.",    "ETR": "Entergy Corporation",    "ETSY": "Etsy Inc.",
    "EVC": "Entravision Communications Corporation",    "EVER": "EverQuote Inc.",    "EVR": "Evercore Inc.",    "EVRG": "Evergy Inc.",
    "EVTC": "Evertec Inc.",    "EW": "Edwards Lifesciences Corporation",    "EWBC": "East West Bancorp Inc.",    "EWTX": "Edgewise Therapeutics Inc.",
    "EXC": "Exelon Corporation",    "EXE": "Expand Energy Corporation",    "EXEL": "Exelixis Inc.",    "EXLS": "ExlService Holdings Inc.",
    "EXP": "Eagle Materials Inc",    "EXPD": "Expeditors International of Washington I",    "EXPE": "Expedia Group Inc.",    "EXPO": "Exponent Inc.",
    "EXR": "Extra Space Storage Inc",    "EXTR": "Extreme Networks Inc.",    "EYE": "National Vision Holdings Inc.",    "EYPT": "EyePoint Inc.",
    "EZPW": "EZCORP Inc.",    "F": "Ford Motor Company",    "FA": "First Advantage Corporation",    "FAF": "First American Corporation (New)",
    "FANG": "Diamondback Energy Inc.",    "FAST": "Fastenal Company",    "FBIN": "Fortune Brands Innovations Inc.",    "FBK": "FB Financial Corporation",
    "FBNC": "First Bancorp",    "FBP": "First BanCorp. New",    "FBYD": "Falcon's Beyond Global Inc.",    "FCEL": "FuelCell Energy Inc.",
    "FCF": "First Commonwealth Financial Corporation",    "FCFS": "FirstCash Holdings Inc.",    "FCN": "FTI Consulting Inc.",    "FCX": "Freeport-McMoRan Inc.",
    "FDMT": "4D Molecular Therapeutics Inc.",    "FDS": "FactSet Research Systems Inc.",    "FDUS": "Fidus Investment Corporation",    "FDX": "FedEx Corporation",
    "FDXF": "FedEx Freight Holding Company Inc.",    "FE": "FirstEnergy Corp.",    "FER": "Ferrovial N.V.",    "FERG": "Ferguson Enterprises Inc.",
    "FFBC": "First Financial Bancorp.",    "FFIN": "First Financial Bankshares Inc.",    "FFIV": "F5 Inc.",    "FG": "F&G Annuities & Life Inc.",
    "FHB": "First Hawaiian Inc.",    "FHI": "Federated Hermes Inc.",    "FHN": "First Horizon Corporation",    "FIBK": "First Interstate BancSystem Inc. Common ",
    "FIG": "Figma Inc.",    "FIGR": "Figure Technology Solutions Inc.",    "FIGS": "FIGS Inc.",    "FIS": "Fidelity National Information Services I",
    "FISV": "Fiserv Inc.",    "FITB": "Fifth Third Bancorp",    "FIVE": "Five Below Inc.",    "FIVN": "Five9 Inc.",
    "FIX": "Comfort Systems USA Inc.",    "FIZZ": "National Beverage Corp.",    "FLEX": "Flex Ltd.",    "FLG": "Flagstar Bank N.A.",
    "FLGT": "Fulgent Genetics Inc.",    "FLNC": "Fluence Energy Inc.",    "FLNG": "FLEX LNG Ltd.",    "FLOC": "Flowco Holdings Inc.",
    "FLR": "Fluor Corporation",    "FLS": "Flowserve Corporation",    "FLUT": "Flutter Entertainment plc",    "FLY": "Firefly Aerospace Inc.",
    "FLYW": "Flywire Corporation Voting",    "FMC": "FMC Corporation",    "FMNB": "Farmers National Banc Corp.",    "FMX": "Fomento Economico Mexicano S.A.B. de C.V",
    "FN": "Fabrinet",    "FNB": "F.N.B. Corporation",    "FND": "Floor & Decor Holdings Inc.",    "FNF": "Fidelity National Financial Inc.",
    "FNV": "Franco-Nevada Corporation",    "FORM": "FormFactor Inc. FormFactor Inc.",    "FOUR": "Shift4 Payments Inc.",    "FOX": "Fox Corporation",
    "FOXA": "Fox Corporation",    "FOXF": "Fox Factory Holding Corp.",    "FPS": "Forgent Power Solutions Inc.",    "FRHC": "Freedom Holding Corp.",
    "FRME": "First Merchants Corporation",    "FRO": "Frontline Plc",    "FROG": "JFrog Ltd.",    "FRPT": "Freshpet Inc.",
    "FRSH": "Freshworks Inc.",    "FRVO": "Fervo Energy Company",    "FSK": "FS KKR Capital Corp.",    "FSLR": "First Solar Inc.",
    "FSLY": "Fastly Inc.",    "FSS": "Federal Signal Corporation",    "FSUN": "FirstSun Capital Bancorp",    "FTAI": "FTAI Aviation Ltd.",
    "FTDR": "Frontdoor Inc.",    "FTI": "TechnipFMC plc Ordinary Share",    "FTNT": "Fortinet Inc.",    "FTRE": "Fortrea Holdings Inc.",
    "FTS": "Fortis Inc. Common Shares",    "FTV": "Fortive Corporation",    "FUBO": "FuboTV Inc.",    "FUL": "H. B. Fuller Company",
    "FULT": "Fulton Financial Corporation",    "FUN": "Six Flags Entertainment Corporation Comm",    "FWONK": "Liberty Media Corporation Series C Liber",    "FWRG": "First Watch Restaurant Group Inc.",
    "G": "Genpact Limited",    "GAP": "Gap Inc. (The)",    "GATX": "GATX Corporation",    "GBCI": "Glacier Bancorp Inc.",
    "GBDC": "Golub Capital BDC Inc.",    "GBX": "Greenbrier Companies Inc. (The)",    "GCMG": "GCM Grosvenor Inc.",    "GCT": "GigaCloud Technology Inc",
    "GD": "General Dynamics Corporation",    "GDDY": "GoDaddy Inc.",    "GDOT": "Green Dot Corporation",    "GDS": "GDS Holdings Limited ADS",
    "GE": "GE Aerospace",    "GEHC": "GE HealthCare Technologies Inc.",    "GEN": "Gen Digital Inc.",    "GENB": "Generate Biomedicines Inc.",
    "GEO": "Geo Group Inc (The) REIT",    "GEV": "GE Vernova Inc.",    "GFF": "Griffon Corporation",    "GFL": "GFL Environmental Inc. Subordinate votin",
    "GFS": "GlobalFoundries Inc.",    "GGG": "Graco Inc.",    "GH": "Guardant Health Inc.",    "GIII": "G-III Apparel Group LTD.",
    "GIL": "Gildan Activewear Inc.",    "GILD": "Gilead Sciences Inc.",    "GILT": "Gilat Satellite Networks Ltd.",    "GIS": "General Mills Inc.",
    "GKOS": "Glaukos Corporation",    "GL": "Globe Life Inc.",    "GLAS": "Glass House Brands Inc. Subordinate Voti",    "GLBE": "Global-E Online Ltd.",
    "GLIBK": "Liberty Capital Corporation Series C GCI",    "GLNG": "Golar Lng Ltd",    "GLOB": "Globant S.A. Common Shares",    "GLPI": "Gaming and Leisure Properties Inc.",
    "GLUE": "Monte Rosa Therapeutics Inc.",    "GLW": "Corning Incorporated",    "GLXY": "Galaxy Digital Inc.",    "GM": "General Motors Company",
    "GMAB": "Genmab A/S ADS",    "GME": "GameStop Corporation",    "GMED": "Globus Medical Inc.",    "GMRS": "GMR Solutions Inc.",
    "GNRC": "Generac Holdlings Inc.",    "GNTX": "Gentex Corporation",    "GOLD": "Gold.com Inc.",    "GOOG": "Alphabet Inc.",
    "GOOGL": "Alphabet Inc.",    "GPC": "Genuine Parts Company",    "GPGI": "GPGI Inc.",    "GPK": "Graphic Packaging Holding Company",
    "GPN": "Global Payments Inc.",    "GPOR": "Gulfport Energy Corporation Common Share",    "GPRE": "Green Plains Inc.",    "GRAL": "GRAIL Inc.",
    "GRBK": "Green Brick Partners Inc.",    "GRDN": "Guardian Pharmacy Services Inc.",    "GRMN": "Garmin Ltd. Common Stock (Switzerland)",    "GRND": "Grindr Inc.",
    "GRPN": "Groupon Inc.",    "GRRR": "Gorilla Technology Group Inc. Ordinary s",    "GS": "Goldman Sachs Group Inc. (The)",    "GSAT": "Globalstar Inc.",
    "GSHD": "Goosehead Insurance Inc.",    "GTES": "Gates Industrial Corporation plc",    "GTLB": "GitLab Inc.",    "GTLS": "Chart Industries Inc.",
    "GTX": "Garrett Motion Inc.",    "GTY": "Getty Realty Corporation",    "GVA": "Granite Construction Incorporated",    "GWRE": "Guidewire Software Inc.",
    "GWW": "W.W. Grainger Inc.",    "GXO": "GXO Logistics Inc.",    "H": "Hyatt Hotels Corporation",    "HAE": "Haemonetics Corporation",
    "HAL": "Halliburton Company",    "HALO": "Halozyme Therapeutics Inc.",    "HAPN": "Happen Inc.",    "HAS": "Hasbro Inc.",
    "HASI": "HA Sustainable Infrastructure Capital In",    "HAWK": "HawkEye 360 Inc.",    "HAYW": "Hayward Holdings Inc.",    "HBAN": "Huntington Bancshares Incorporated",
    "HBM": "Hudbay Minerals Inc.",    "HBNC": "Horizon Bancorp Inc.",    "HCA": "HCA Healthcare Inc.",    "HCC": "Warrior Met Coal Inc.",
    "HCSG": "Healthcare Services Group Inc.",    "HD": "Home Depot Inc. (The)",    "HDB": "HDFC Bank Limited",    "HE": "Hawaiian Electric Industries Inc.",
    "HEI": "Heico Corporation",    "HELE": "Helen of Troy Limited",    "HESM": "Hess Midstream LP",    "HFWA": "Heritage Financial Corporation",
    "HG": "Hamilton Insurance Group Ltd.",    "HGV": "Hilton Grand Vacations Inc.",    "HHH": "Howard Hughes Holdings Inc.",    "HIG": "The Hartford Insurance Group Inc.",
    "HII": "Huntington Ingalls Industries Inc.",    "HIMS": "Hims & Hers Health Inc.",    "HIW": "Highwoods Properties Inc.",    "HL": "Hecla Mining Company",
    "HLF": "Herbalife Ltd. Common Shares",    "HLI": "Houlihan Lokey Inc.",    "HLIO": "Helios Technologies Inc.",    "HLIT": "Harmonic Inc.",
    "HLNE": "Hamilton Lane Incorporated",    "HLT": "Hilton Worldwide Holdings Inc.",    "HMC": "Honda Motor Company Ltd.",    "HMH": "HMH Holding Inc.",
    "HMY": "Harmony Gold Mining Company Limited",    "HNGE": "Hinge Health Inc.",    "HNI": "HNI Corporation",    "HNRG": "Hallador Energy Company",
    "HOG": "Harley-Davidson Inc.",    "HOMB": "Home BancShares Inc.",    "HON": "Honeywell International Inc.",    "HONA": "Honeywell Aerospace Inc.",
    "HOOD": "Robinhood Markets Inc.",    "HOPE": "Hope Bancorp Inc.",    "HP": "Helmerich & Payne Inc.",    "HPE": "Hewlett Packard Enterprise Company",
    "HPP": "Hudson Pacific Properties Inc.",    "HPQ": "HP Inc.",    "HQ": "Horizon Quantum Holdings Ltd.",    "HQY": "HealthEquity Inc.",
    "HRB": "H&R Block Inc.",    "HRI": "Herc Holdings Inc.",    "HRL": "Hormel Foods Corporation",    "HRMY": "Harmony Biosciences Holdings Inc.",
    "HROW": "Harrow Inc.",    "HRTG": "Heritage Insurance Holdings Inc.",    "HSBC": "HSBC Holdings plc.",    "HSIC": "Henry Schein Inc.",
    "HST": "Host Hotels & Resorts Inc.",    "HSY": "The Hershey Company",    "HTFL": "Heartflow Inc.",    "HTGC": "Hercules Capital Inc.",
    "HTH": "Hilltop Holdings Inc.",    "HTLD": "Heartland Express Inc.",    "HTO": "H2O America",    "HUBB": "Hubbell Inc",
    "HUBG": "Hub Group Inc.",    "HUBS": "HubSpot Inc.",    "HUM": "Humana Inc.",    "HUN": "Huntsman Corporation",
    "HURN": "Huron Consulting Group Inc.",    "HUT": "Hut 8 Corp.",    "HWC": "Hancock Whitney Corporation",    "HWM": "Howmet Aerospace Inc.",
    "HXL": "Hexcel Corporation",    "HYMC": "Hycroft Mining Holding Corporation",    "IAG": "Iamgold Corporation",    "IART": "Integra LifeSciences Holdings Corporatio",
    "IBKR": "Interactive Brokers Group Inc.",    "IBM": "International Business Machines Corporat",    "IBN": "ICICI Bank Limited",    "IBOC": "International Bancshares Corporation",
    "IBP": "Installed Building Products Inc.",    "ICE": "Intercontinental Exchange Inc.",    "ICHR": "Ichor Holdings",    "ICLR": "ICON plc",
    "IDA": "IDACORP Inc.",    "IDXX": "IDEXX Laboratories Inc.",    "IDYA": "IDEAYA Biosciences Inc.",    "IESC": "IES Holdings Inc.",
    "IEX": "IDEX Corporation",    "IFF": "International Flavors & Fragrances Inc.",    "IFS": "Intercorp Financial Services Inc. Common",    "IIIV": "i3 Verticals Inc.",
    "IIPR": "Innovative Industrial Properties Inc.",    "ILMN": "Illumina Inc.",    "IMAX": "Imax Corporation",    "IMNM": "Immunome Inc.",
    "IMO": "Imperial Oil Limited",    "IMVT": "Immunovant Inc.",    "INCY": "Incyte Corp.",    "INDB": "Independent Bank Corp.",
    "INDV": "Indivior Pharmaceuticals Inc.",    "INFQ": "Infleqtion Inc.",    "ING": "ING Group N.V.",    "INGM": "Ingram Micro Holding Corporation",
    "INGR": "Ingredion Incorporated",    "INIO": "INNIO N.V.",    "INMD": "InMode Ltd.",    "INNV": "InnovAge Holding Corp.",
    "INOD": "Innodata Inc.",    "INSM": "Insmed Incorporated",    "INSP": "Inspire Medical Systems Inc.",    "INSW": "International Seaways Inc.",
    "INTA": "Intapp Inc.",    "INTC": "Intel Corporation",    "INTU": "Intuit Inc.",    "INVA": "Innoviva Inc.",
    "INVH": "Invitation Homes Inc.",    "INVX": "Innovex International Inc.",    "IONQ": "IonQ Inc.",    "IONS": "Ionis Pharmaceuticals Inc.",
    "IOT": "Samsara Inc.",    "IP": "International Paper Company",    "IPAR": "Interparfums Inc.",    "IQV": "IQVIA Holdings Inc.",
    "IR": "Ingersoll Rand Inc.",    "IRDM": "Iridium Communications Inc",    "IREN": "IREN Limited",    "IRM": "Iron Mountain Incorporated (Delaware)Com",
    "IRON": "Disc Medicine Inc.",    "IRTC": "iRhythm Holdings Inc.",    "ISRG": "Intuitive Surgical Inc.",    "IT": "Gartner Inc.",
    "ITGR": "Integer Holdings Corporation",    "ITRI": "Itron Inc.",    "ITT": "ITT Inc.",    "ITW": "Illinois Tool Works Inc.",
    "IVT": "InvenTrust Properties Corp.",    "IVZ": "Invesco Ltd",    "J": "Jacobs Solutions Inc.",    "JAN": "Janus Living Inc.",
    "JANX": "Janux Therapeutics Inc.",    "JAZZ": "Jazz Pharmaceuticals plc Common Stock (I",    "JBGS": "JBG SMITH Properties Common Shares",    "JBHT": "J.B. Hunt Transport Services Inc.",
    "JBIO": "Jade Biosciences Inc.",    "JBL": "Jabil Inc.",    "JBS": "JBS N.V.",    "JBTM": "JBT Marel Corporation",
    "JCI": "Johnson Controls International plc Ordin",    "JEF": "Jefferies Financial Group Inc.",    "JHX": "James Hardie Industries plc.",    "JKHY": "Jack Henry & Associates Inc.",
    "JLL": "Jones Lang LaSalle Incorporated",    "JNJ": "Johnson & Johnson",    "JOE": "St. Joe Company (The)",    "JPM": "JP Morgan Chase & Co.",
    "JXN": "Jackson Financial Inc.",    "KARD": "Kardigan Inc.",    "KB": "KB Financial Group Inc",    "KBH": "KB Home",
    "KBR": "KBR Inc.",    "KD": "Kyndryl Holdings Inc.",    "KDP": "Keurig Dr Pepper Inc.",    "KEP": "Korea Electric Power Corporation",
    "KEX": "Kirby Corporation",    "KEY": "KeyCorp",    "KEYS": "Keysight Technologies Inc.",    "KFY": "Korn Ferry",
    "KGC": "Kinross Gold Corporation",    "KGS": "Kodiak Gas Services Inc.",    "KHC": "The Kraft Heinz Company",    "KIM": "Kimco Realty Corporation (HC)",
    "KKR": "KKR & Co. Inc.",    "KLAC": "KLA Corporation",    "KLAR": "Klarna Group plc",    "KLIC": "Kulicke and Soffa Industries Inc.",
    "KLRA": "Kailera Therapeutics Inc.",    "KMB": "Kimberly-Clark Corporation",    "KMI": "Kinder Morgan Inc.",    "KMPR": "Kemper Corporation",
    "KMT": "Kennametal Inc.",    "KMTS": "Kestra Medical Technologies Ltd.",    "KMX": "CarMax Inc",    "KN": "Knowles Corporation",
    "KNF": "Knife Riv Holding Co.",    "KNSA": "Kiniksa Pharmaceuticals International pl",    "KNSL": "Kinsale Capital Group Inc.",    "KNTK": "Kinetik Holdings Inc.",
    "KNX": "Knight-Swift Transportation Holdings Inc",    "KO": "Coca-Cola Company (The)",    "KOD": "Kodiak Sciences Inc",    "KR": "Kroger Company (The)",
    "KRC": "Kilroy Realty Corporation",    "KRMN": "Karman Holdings Inc.",    "KSS": "Kohl's Corporation",    "KT": "KT Corporation",
    "KTB": "Kontoor Brands Inc.",    "KTOS": "Kratos Defense & Security Solutions Inc.",    "KURA": "Kura Oncology Inc.",    "KVUE": "Kenvue Inc.",
    "KVYO": "Klaviyo Inc. Series A",    "KYIV": "Kyivstar Group Ltd. Common Shares",    "KYMR": "Kymera Therapeutics Inc.",    "L": "Loews Corporation",
    "LAMR": "Lamar Advertising Company",    "LASR": "nLIGHT Inc.",    "LAUR": "Laureate Education Inc.",    "LAZ": "Lazard Inc.",
    "LB": "LandBridge Company LLC",    "LBRDK": "Liberty Broadband Corporation",    "LBRT": "Liberty Energy Inc.",    "LBTYA": "Liberty Global Ltd.",
    "LBTYK": "Liberty Global Ltd.",    "LCII": "LCI Industries",    "LCLN": "Lincoln International Inc.",    "LDOS": "Leidos Holdings Inc.",
    "LEA": "Lear Corporation",    "LECO": "Lincoln Electric Holdings Inc. Common Sh",    "LEG": "Leggett & Platt Incorporated",    "LEN": "Lennar Corporation",
    "LEU": "Centrus Energy Corp.",    "LEVI": "Levi Strauss & Co",    "LFST": "LifeStance Health Group Inc.",    "LFTO": "Liftoff Mobile Inc.",
    "LFUS": "Littelfuse Inc.",    "LGIH": "LGI Homes Inc.",    "LGN": "Legence Corp.",    "LGND": "Ligand Pharmaceuticals Incorporated",
    "LH": "Labcorp Holdings Inc.",    "LHX": "L3Harris Technologies Inc.",    "LIF": "Life360 Inc.",    "LIFE": "Ethos Technologies Inc.",
    "LII": "Lennox International Inc.",    "LIN": "Linde plc",    "LINC": "Lincoln Educational Services Corporation",    "LIND": "Lindblad Expeditions Holdings Inc.",
    "LINE": "Lineage Inc.",    "LION": "Lionsgate Studios Corp Common Shares",    "LITE": "Lumentum Holdings Inc.",    "LIVN": "LivaNova PLC",
    "LKQ": "LKQ Corporation",    "LLY": "Eli Lilly and Company",    "LLYVA": "Liberty Live Holdings Inc. Series A Libe",    "LLYVK": "Liberty Live Holdings Inc. Series C Libe",
    "LMAT": "LeMaitre Vascular Inc.",    "LMND": "Lemonade Inc.",    "LMRI": "Lumexa Imaging Holdings Inc.",    "LMT": "Lockheed Martin Corporation",
    "LNC": "Lincoln National Corporation",    "LNG": "Cheniere Energy Inc.",    "LNT": "Alliant Energy Corporation",    "LNTH": "Lantheus Holdings Inc.",
    "LOAR": "Loar Holdings Inc.",    "LOCO": "El Pollo Loco Holdings Inc.",    "LOGI": "Logitech International S.A.",    "LOMA": "Loma Negra Compania Industrial Argentina",
    "LOPE": "Grand Canyon Education Inc.",    "LOW": "Lowe's Companies Inc.",    "LPG": "Dorian LPG Ltd.",    "LPLA": "LPL Financial Holdings Inc.",
    "LPTH": "LightPath Technologies Inc.",    "LPX": "Louisiana-Pacific Corporation",    "LQDA": "Liquidia Corporation",    "LRCX": "Lam Research Corporation",
    "LRN": "Stride Inc.",    "LSCC": "Lattice Semiconductor Corporation",    "LSPD": "Lightspeed Commerce Inc. Subordinate Vot",    "LSTR": "Landstar System Inc.",
    "LTC": "LTC Properties Inc.",    "LTH": "Life Time Group Holdings Inc.",    "LULU": "lululemon athletica inc.",    "LUNR": "Intuitive Machines Inc.",
    "LUV": "Southwest Airlines Company",    "LVS": "Las Vegas Sands Corp.",    "LW": "Lamb Weston Holdings Inc.",    "LXU": "LSB Industries Inc.",
    "LYB": "LyondellBasell Industries NV",    "LYFT": "Lyft Inc.",    "LYTS": "LSI Industries Inc.",    "LYV": "Live Nation Entertainment Inc.",
    "LZB": "La-Z-Boy Incorporated",    "M": "Macy's Inc",    "MA": "Mastercard Incorporated",    "MAA": "Mid-America Apartment Communities Inc.",
    "MAC": "Macerich Company (The)",    "MAIN": "Main Street Capital Corporation",    "MAIR": "Madison Air Solutions Corporation",    "MAMA": "Mama's Creations Inc.",
    "MAN": "ManpowerGroup",    "MANE": "Veradermics Incorporated",    "MANH": "Manhattan Associates Inc.",    "MAR": "Marriott International",
    "MARA": "MARA Holdings Inc.",    "MAS": "Masco Corporation",    "MAT": "Mattel Inc.",    "MATW": "Matthews International Corporation",
    "MATX": "Matson Inc.",    "MAX": "MediaAlpha Inc.",    "MAZE": "Maze Therapeutics Inc.",    "MBGL": "Mobility Global Inc.",
    "MBUU": "Malibu Boats Inc.",    "MBX": "MBX Biosciences Inc.",    "MC": "Moelis & Company",    "MCD": "McDonald's Corporation",
    "MCHB": "Mechanics Bancorp",    "MCHP": "Microchip Technology Incorporated",    "MCK": "McKesson Corporation",    "MCO": "Moody's Corporation",
    "MCY": "Mercury General Corporation",    "MD": "Pediatrix Medical Group Inc.",    "MDA": "MDA Space Ltd. Common Shares",    "MDB": "MongoDB Inc.",
    "MDGL": "Madrigal Pharmaceuticals Inc.",    "MDLN": "Medline Inc.",    "MDLZ": "Mondelez International Inc.",    "MDT": "Medtronic plc.",
    "MDU": "MDU Resources Group Inc. Common Stock (H",    "MEC": "Mayville Engineering Company Inc.",    "MEDP": "Medpace Holdings Inc.",    "MEI": "Methode Electronics Inc.",
    "MELI": "MercadoLibre Inc.",    "MEOH": "Methanex Corporation",    "MET": "MetLife Inc.",    "META": "Meta Platforms Inc.",
    "METC": "Ramaco Resources Inc.",    "MFC": "Manulife Financial Corporation",    "MFIC": "MidCap Financial Investment Corporation",    "MGA": "Magna International Inc.",
    "MGEE": "MGE Energy Inc",    "MGM": "MGM Resorts International",    "MGNI": "Magnite Inc.",    "MGTX": "MeiraGTx Holdings plc",
    "MGY": "Magnolia Oil & Gas Corporation",    "MH": "McGraw Hill Inc.",    "MHK": "Mohawk Industries Inc.",    "MIAX": "Miami International Holdings Inc.",
    "MICC": "The Magnum Ice Cream Company N.V.",    "MIDD": "Middleby Corporation (The)",    "MIR": "Mirion Technologies Inc.",    "MIRM": "Mirum Pharmaceuticals Inc.",
    "MITK": "Mitek Systems Inc.",    "MKC": "McCormick & Company Incorporated",    "MKSI": "MKS Inc.",    "MKTX": "MarketAxess Holdings Inc.",
    "MLI": "Mueller Industries Inc.",    "MLKN": "MillerKnoll Inc.",    "MLM": "Martin Marietta Materials Inc.",    "MLTX": "MoonLake Immunotherapeutics",
    "MLYS": "Mineralys Therapeutics Inc.",    "MMED": "MiniMed Group Inc.",    "MMM": "3M Company",    "MMS": "Maximus Inc.",
    "MMSI": "Merit Medical Systems Inc.",    "MMYT": "MakeMyTrip Limited",    "MNDY": "monday.com Ltd.",    "MNRO": "Monro Inc.",
    "MNST": "Monster Beverage Corporation",    "MNTN": "MNTN Inc.",    "MO": "Altria Group Inc.",    "MOD": "Modine Manufacturing Company",
    "MOH": "Molina Healthcare Inc",    "MORN": "Morningstar Inc.",    "MOS": "Mosaic Company (The)",    "MP": "MP Materials Corp.",
    "MPC": "Marathon Petroleum Corporation",    "MPLT": "MapLight Therapeutics Inc.",    "MPWR": "Monolithic Power Systems Inc.",    "MQ": "Marqeta Inc.",
    "MRAM": "Everspin Technologies Inc.",    "MRCY": "Mercury Systems Inc",    "MRK": "Merck & Company Inc. Common Stock (new)",    "MRNA": "Moderna Inc.",
    "MRP": "Millrose Properties Inc.",    "MRSH": "Marsh",    "MRTN": "Marten Transport Ltd.",    "MRVL": "Marvell Technology Inc.",
    "MRX": "Marex Group Limited",    "MS": "Morgan Stanley",    "MSA": "MSA Safety Incorporated",    "MSCI": "MSCI Inc.",
    "MSFT": "Microsoft Corporation",    "MSGE": "Madison Square Garden Entertainment Corp",    "MSGS": "Madison Square Garden Sports Corp.",    "MSI": "Motorola Solutions Inc.",
    "MSM": "MSC Industrial Direct Company Inc.",    "MSTR": "Strategy Inc Common Stock",    "MT": "Arcelor Mittal NY Registry Shares NEW",    "MTB": "M&T Bank Corporation",
    "MTCH": "Match Group Inc.",    "MTDR": "Matador Resources Company",    "MTG": "MGIC Investment Corporation",    "MTH": "Meritage Homes Corporation",
    "MTN": "Vail Resorts Inc.",    "MTRN": "Materion Corporation",    "MTSI": "MACOM Technology Solutions Holdings Inc.",    "MTUS": "Metallus Inc. Common Shares",
    "MTX": "Minerals Technologies Inc.",    "MTZ": "MasTec Inc.",    "MU": "Micron Technology Inc.",    "MUFG": "Mitsubishi UFJ Financial Group Inc.",
    "MUR": "Murphy Oil Corporation",    "MUSA": "Murphy USA Inc.",    "MUX": "McEwen Inc.",    "MWA": "MUELLER WATER PRODUCTS",
    "MWH": "SOLV Energy Inc.",    "MXL": "MaxLinear Inc.",    "MYE": "Myers Industries Inc.",    "MYRG": "MYR Group Inc.",
    "NAMS": "NewAmsterdam Pharma Company N.V.",    "NATL": "NCR Atleos Corporation",    "NAVN": "Navan Inc.",    "NBHC": "National Bank Holdings Corporation",
    "NBIS": "Nebius Group N.V.",    "NBIX": "Neurocrine Biosciences Inc.",    "NBR": "Nabors Industries Ltd.",    "NBTB": "NBT Bancorp Inc.",
    "NCLH": "Norwegian Cruise Line Holdings Ltd.",    "NCNO": "nCino Inc.",    "NDAQ": "Nasdaq Inc.",    "NDSN": "Nordson Corporation",
    "NE": "Noble Corporation plc A",    "NEE": "NextEra Energy Inc.",    "NEM": "Newmont Corporation",    "NEO": "NeoGenomics Inc.",
    "NESR": "National Energy Services Reunited Corp",    "NET": "Cloudflare Inc.",    "NEXA": "Nexa Resources S.A. Common Shares",    "NFG": "National Fuel Gas Company",
    "NFLX": "Netflix Inc.",    "NGNE": "Neurogene Inc.",    "NHI": "National Health Investors Inc.",    "NHP": "National Healthcare Properties Inc.",
    "NI": "NiSource Inc",    "NJR": "NewJersey Resources Corporation",    "NKE": "Nike Inc.",    "NKTR": "Nektar Therapeutics",
    "NLY": "Annaly Capital Management Inc.",    "NMIH": "NMI Holdings Inc.",    "NMRK": "Newmark Group Inc.",    "NN": "NextNav Inc.",
    "NNE": "Nano Nuclear Energy Inc.",    "NNN": "NNN REIT Inc.",    "NOC": "Northrop Grumman Corporation",    "NOG": "Northern Oil and Gas Inc.",
    "NOMD": "Nomad Foods Limited",    "NOV": "NOV Inc.",    "NOVT": "Novanta Inc.",    "NOW": "ServiceNow Inc.",
    "NP": "Neptune Insurance Holdings Inc.",    "NPB": "Northpointe Bancshares Inc.",    "NPKI": "NPK International Inc.",    "NRG": "NRG Energy Inc.",
    "NRIX": "Nurix Therapeutics Inc. Common stock",    "NSC": "Norfolk Southern Corporation",    "NSIT": "Insight Enterprises Inc.",    "NSP": "Insperity Inc.",
    "NTAP": "NetApp Inc.",    "NTCT": "NetScout Systems Inc.",    "NTLA": "Intellia Therapeutics Inc.",    "NTNX": "Nutanix Inc.",
    "NTR": "Nutrien Ltd. Common Shares",    "NTRA": "Natera Inc.",    "NTSK": "Netskope Inc.",    "NTST": "NetSTREIT Corp.",
    "NU": "Nu Holdings Ltd.",    "NUE": "Nucor Corporation",    "NUVL": "Nuvalent Inc.",    "NVCR": "NovoCure Limited",
    "NVCT": "Nuvectis Pharma Inc.",    "NVDA": "NVIDIA Corporation",    "NVGS": "Navigator Holdings Ltd.",    "NVMI": "Nova Ltd.",
    "NVO": "Novo Nordisk A/S",    "NVRI": "Enviri Corporation",    "NVS": "Novartis AG",    "NVST": "Envista Holdings Corporation",
    "NVT": "nVent Electric plc",    "NVTS": "Navitas Semiconductor Corporation",    "NWBI": "Northwest Bancshares Inc.",    "NWE": "NorthWestern Energy Group Inc.",
    "NWS": "News Corporation",    "NWSA": "News Corporation",    "NX": "Quanex Building Products Corporation",    "NXPI": "NXP Semiconductors N.V.",
    "NXST": "Nexstar Media Group Inc.",    "NXT": "Nextpower Inc.",    "NYT": "New York Times Company (The)",    "O": "Realty Income Corporation",
    "OBDC": "Blue Owl Capital Corporation",    "OC": "Owens Corning Inc Common Stock New",    "OCFC": "OceanFirst Financial Corp.",    "OCS": "Oculis Holding AG Ordinary shares",
    "OCSL": "Oaktree Specialty Lending Corporation",    "OCTV": "Octave Intelligence plc",    "ODD": "ODDITY Tech Ltd.",    "ODFL": "Old Dominion Freight Line Inc.",
    "ODTX": "Odyssey Therapeutics Inc.",    "OFG": "OFG Bancorp",    "OFRM": "Once Upon a Farm PBC",    "OGE": "OGE Energy Corp",
    "OGN": "Organon & Co.",    "OGS": "ONE Gas Inc.",    "OHI": "Omega Healthcare Investors Inc.",    "OII": "Oceaneering International Inc.",
    "OKE": "ONEOK Inc.",    "OKLO": "Oklo Inc.",    "OKTA": "Okta Inc.",    "OLED": "Universal Display Corporation",
    "OLLI": "Ollie's Bargain Outlet Holdings Inc.",    "OLMA": "Olema Pharmaceuticals Inc.",    "OLN": "Olin Corporation",    "OMC": "Omnicom Group Inc.",
    "OMCL": "Omnicell Inc. Common Stock ($0.001 par v",    "OMDA": "Omada Health Inc.",    "OMF": "OneMain Holdings Inc.",    "ON": "ON Semiconductor Corporation",
    "ONB": "Old National Bancorp",    "ONON": "On Holding AG",    "ONT": "Onterris Inc.",    "ONTO": "Onto Innovation Inc.",
    "OOMA": "Ooma Inc.",    "OPCH": "Option Care Health Inc.",    "OPFI": "OppFi Inc.",    "OPLN": "OPENLANE Inc.",
    "OR": "OR Royalties Inc. Common Shares",    "ORA": "Ormat Technologies Inc.",    "ORCL": "Oracle Corporation",    "ORI": "Old Republic International Corporation",
    "ORIC": "Oric Pharmaceuticals Inc.",    "ORKA": "Oruka Therapeutics Inc.",    "ORLY": "O'Reilly Automotive Inc.",    "ORN": "Orion Group Holdings Inc. Common",
    "OSBC": "Old Second Bancorp Inc.",    "OSCR": "Oscar Health Inc.",    "OSK": "Oshkosh Corporation (Holding Company)Com",    "OSPN": "OneSpan Inc.",
    "OSW": "OneSpaWorld Holdings Limited Common Shar",    "OTEX": "Open Text Corporation Common Shares",    "OTF": "Blue Owl Technology Finance Corp.",    "OTIS": "Otis Worldwide Corporation",
    "OUST": "Ouster Inc.",    "OUT": "OUTFRONT Media Inc.",    "OVV": "Ovintiv Inc. (DE)",    "OXM": "Oxford Industries Inc.",
    "OXY": "Occidental Petroleum Corporation",    "OZK": "Bank OZK",    "P": "Everpure Inc.",    "PAAS": "Pan American Silver Corp.",
    "PACS": "PACS Group Inc.",    "PAHC": "Phibro Animal Health Corporation",    "PAM": "Pampa Energia S.A.",    "PANW": "Palo Alto Networks Inc.",
    "PAR": "PAR Technology Corporation",    "PARR": "Par Pacific Holdings Inc.",    "PATH": "UiPath Inc.",    "PATK": "Patrick Industries Inc.",
    "PAX": "Patria Investments Limited",    "PAY": "Paymentus Holdings Inc.",    "PAYC": "Paycom Software Inc.",    "PAYP": "PayPay Corporation American Depository S",
    "PAYX": "Paychex Inc.",    "PB": "Prosperity Bancshares Inc.",    "PBA": "Pembina Pipeline Corp.",    "PBF": "PBF Energy Inc.",
    "PBH": "Prestige Consumer Healthcare Inc.",    "PBI": "Pitney Bowes Inc.",    "PBLS": "Parabilis Medicines Inc.",    "PBR": "Petroleo Brasileiro S.A. Petrobras ADS",
    "PCAR": "PACCAR Inc.",    "PCG": "Pacific Gas & Electric Co.",    "PCOR": "Procore Technologies Inc.",    "PCRX": "Pacira BioSciences Inc.",
    "PCTY": "Paylocity Holding Corporation",    "PCVX": "Vaxcyte Inc.",    "PD": "PagerDuty Inc.",    "PDFS": "PDF Solutions Inc.",
    "PECO": "Phillips Edison & Company Inc.",    "PEG": "Public Service Enterprise Group Incorpor",    "PEGA": "Pegasystems Inc.",    "PEN": "Penumbra Inc.",
    "PENG": "Penguin Solutions Inc.",    "PENN": "PENN Entertainment Inc.",    "PEP": "PepsiCo Inc.",    "PFE": "Pfizer Inc.",
    "PFG": "Principal Financial Group Inc",    "PFGC": "Performance Food Group Company",    "PFS": "Provident Financial Services Inc",    "PFSI": "PennyMac Financial Services Inc.",
    "PG": "Procter & Gamble Company (The)",    "PGNY": "Progyny Inc.",    "PGR": "Progressive Corporation (The)",    "PGY": "Pagaya Technologies Ltd.",
    "PH": "Parker-Hannifin Corporation",    "PHAT": "Phathom Pharmaceuticals Inc.",    "PHG": "Koninklijke Philips N.V. NY Registry Sha",    "PHIN": "PHINIA Inc.",
    "PHM": "PulteGroup Inc.",    "PHR": "Phreesia Inc.",    "PHVS": "Pharvaris N.V.",    "PI": "Impinj Inc.",
    "PICS": "PicS N.V.",    "PII": "Polaris Inc.",    "PINS": "Pinterest Inc.",    "PIPR": "Piper Sandler Companies",
    "PJT": "PJT Partners Inc.",    "PK": "Park Hotels & Resorts Inc.",    "PKE": "Park Aerospace Corp.",    "PKG": "Packaging Corporation of America",
    "PL": "Planet Labs PBC",    "PLAB": "Photronics Inc.",    "PLD": "Prologis Inc.",    "PLGO": "Pelagos Insurance Capital Limited Common",
    "PLNT": "Planet Fitness Inc.",    "PLTR": "Palantir Technologies Inc.",    "PM": "Philip Morris International Inc",    "PNC": "PNC Financial Services Group Inc. (The)",
    "PNFP": "Pinnacle Financial Partners Inc. Common ",    "PNR": "Pentair plc. Ordinary Share",    "PNTG": "The Pennant Group Inc.",    "PNW": "Pinnacle West Capital Corporation",
    "PODD": "Insulet Corporation",    "POOL": "Pool Corporation",    "POR": "Portland General Electric Co",    "POST": "Post Holdings Inc.",
    "POWI": "Power Integrations Inc.",    "POWL": "Powell Industries Inc.",    "PPC": "Pilgrim's Pride Corporation",    "PPG": "PPG Industries Inc.",
    "PPL": "PPL Corporation",    "PPLI": "People Incorporated",    "PPTA": "Perpetua Resources Corp. Common Shares",    "PR": "Permian Resources Corporation",
    "PRAA": "PRA Group Inc.",    "PRAX": "Praxis Precision Medicines Inc.",    "PRCH": "Porch Group Inc.",    "PRCT": "PROCEPT BioRobotics Corporation",
    "PRDO": "Perdoceo Education Corporation",    "PRG": "PROG Holdings Inc.",    "PRGO": "Perrigo Company plc",    "PRGS": "Progress Software Corporation Common Sto",
    "PRIM": "Primoris Services Corporation",    "PRKS": "United Parks & Resorts Inc.",    "PRM": "Perimeter Solutions SA",    "PRMB": "Primo Brands Corporation",
    "PRSU": "Pursuit Attractions and Hospitality Inc.",    "PRU": "Prudential Financial Inc.",    "PRVA": "Privia Health Group Inc.",    "PSA": "Public Storage",
    "PSIX": "Power Solutions International Inc.",    "PSKY": "Paramount Skydance Corporation",    "PSMT": "PriceSmart Inc.",    "PSN": "Parsons Corporation",
    "PSNL": "Personalis Inc.",    "PSO": "Pearson Plc",    "PSUS": "Pershing Square USA Ltd. Common Shares",    "PSX": "Phillips 66",
    "PTC": "PTC Inc.",    "PTCT": "PTC Therapeutics Inc.",    "PTGX": "Protagonist Therapeutics Inc.",    "PTRN": "Pattern Group Inc. Series A",
    "PUBM": "PubMatic Inc.",    "PUK": "Prudential Public Limited Company",    "PUMP": "ProPetro Holding Corp.",    "PVH": "PVH Corp.",
    "PVLA": "Palvella Therapeutics Inc.",    "PWP": "Perella Weinberg Partners",    "PWR": "Quanta Services Inc.",    "PYPL": "PayPal Holdings Inc.",
    "PZZA": "Papa John's International Inc.",    "Q": "Qnity Electronics Inc.",    "QBTS": "D-Wave Quantum Inc. Common Shares",    "QCOM": "QUALCOMM Incorporated",
    "QDEL": "QuidelOrtho Corporation",    "QGEN": "Qiagen N.V. Common Shares",    "QLYS": "Qualys Inc.",    "QNST": "QuinStreet Inc.",
    "QNT": "Quantinuum Inc.",    "QRVO": "Qorvo Inc.",    "QSR": "Restaurant Brands International Inc. Com",    "QTWO": "Q2 Holdings Inc.",
    "QURE": "uniQure N.V.",    "QXO": "QXO Inc.",    "R": "Ryder System Inc.",    "RACE": "Ferrari N.V. Common Shares",
    "RAL": "Ralliant Corporation",    "RAMP": "LiveRamp Holdings Inc.",    "RAPP": "Rapport Therapeutics Inc.",    "RARE": "Ultragenyx Pharmaceutical Inc.",
    "RBA": "RB Global Inc.",    "RBLX": "Roblox Corporation",    "RBRK": "Rubrik Inc.",    "RCAT": "Red Cat Holdings Inc.",
    "RCI": "Rogers Communication Inc.",    "RCL": "Royal Caribbean Cruises Ltd.",    "RCUS": "Arcus Biosciences Inc.",    "RDDT": "Reddit Inc.",
    "RDN": "Radian Group Inc.",    "RDNT": "RadNet Inc.",    "RDW": "Redwire Corporation",    "RDY": "Dr. Reddy's Laboratories Ltd",
    "REAL": "The RealReal Inc.",    "REG": "Regency Centers Corporation",    "REGN": "Regeneron Pharmaceuticals Inc.",    "RELY": "Remitly Global Inc.",
    "REPL": "Replimune Group Inc.",    "REPX": "Riley Exploration Permian Inc.",    "REXR": "Rexford Industrial Realty Inc.",    "REYN": "Reynolds Consumer Products Inc.",
    "REZI": "Resideo Technologies Inc.",    "RF": "Regions Financial Corporation",    "RGA": "Reinsurance Group of America Incorporate",    "RGEN": "Repligen Corporation",
    "RGLD": "Royal Gold Inc.",    "RGNX": "REGENXBIO Inc.",    "RGTI": "Rigetti Computing Inc.",    "RH": "RH",
    "RHI": "Robert Half Inc.",    "RHP": "Ryman Hospitality Properties Inc. (REIT)",    "RIO": "Rio Tinto Plc",    "RIOT": "Riot Platforms Inc.",
    "RIVN": "Rivian Automotive Inc.",    "RJF": "Raymond James Financial Inc.",    "RKLB": "Rocket Lab Corporation",    "RKT": "Rocket Companies Inc.",
    "RL": "Ralph Lauren Corporation",    "RLAY": "Relay Therapeutics Inc.",    "RLI": "RLI Corp. Common Stock (DE)",    "RMBS": "Rambus Inc.",
    "RMD": "ResMed Inc.",    "RMIX": "Suncrete Inc.",    "RNG": "RingCentral Inc.",    "RNR": "RenaissanceRe Holdings Ltd.",
    "RNST": "Renasant Corporation",    "ROAD": "Construction Partners Inc.",    "ROCK": "Gibraltar Industries Inc.",    "ROIV": "Roivant Sciences Ltd. Common Shares",
    "ROK": "Rockwell Automation Inc.",    "ROKU": "Roku Inc.",    "ROL": "Rollins Inc.",    "ROOT": "Root Inc.",
    "ROP": "Roper Technologies Inc.",    "ROST": "Ross Stores Inc.",    "RPM": "RPM International Inc.",    "RPRX": "Royalty Pharma plc",
    "RRC": "Range Resources Corporation",    "RRR": "Red Rock Resorts Inc.",    "RRX": "Regal Rexnord Corporation",    "RS": "Reliance Inc.",
    "RSG": "Republic Services Inc.",    "RSI": "Rush Street Interactive Inc.",    "RTX": "RTX Corporation",    "RUN": "Sunrun Inc.",
    "RUSHA": "Rush Enterprises Inc. Common Stock Cl A",    "RVLV": "Revolve Group Inc.",    "RVMD": "Revolution Medicines Inc.",    "RVTY": "Revvity Inc.",
    "RXO": "RXO Inc.",    "RY": "Royal Bank Of Canada",    "RYAN": "Ryan Specialty Holdings Inc.",    "RYN": "Rayonier Inc. REIT",
    "RYTM": "Rhythm Pharmaceuticals Inc.",    "RYZ": "Ryerson Holding Corporation",    "S": "SentinelOne Inc.",    "SA": "Seabridge Gold Inc. Common Shares New",
    "SAIA": "Saia Inc.",    "SAIC": "Science Applications International Corpo",    "SAIL": "SailPoint Inc.",    "SAN": "Banco Santander S.A. Sponsored ADR (Spai",
    "SANM": "Sanmina Corporation",    "SAP": "SAP  SE ADS",    "SARO": "StandardAero Inc.",    "SBAC": "SBA Communications Corporation",
    "SBCF": "Seacoast Banking Corporation of Florida",    "SBGI": "Sinclair Inc.",    "SBH": "Sally Beauty Holdings Inc. (Name to be c",    "SBLK": "Star Bulk Carriers Corp. Common Shares",
    "SBRA": "Sabra Health Care REIT Inc.",    "SBUX": "Starbucks Corporation",    "SCCO": "Southern Copper Corporation",    "SCHW": "Charles Schwab Corporation (The)",
    "SCI": "Service Corporation International",    "SDGR": "Schrodinger Inc.",    "SDRL": "Seadrill Limited Common Shares",    "SEDG": "SolarEdge Technologies Inc.",
    "SEI": "Solaris Energy Infrastructure Inc.",    "SEIC": "SEI Investments Company",    "SEPN": "Septerna Inc.",    "SEZL": "Sezzle Inc.",
    "SF": "Stifel Financial Corporation",    "SFBS": "ServisFirst Bancshares Inc.",    "SFD": "Smithfield Foods Inc.",    "SFL": "SFL Corporation Ltd",
    "SFM": "Sprouts Farmers Market Inc.",    "SFNC": "Simmons First National Corporation",    "SGHC": "Super Group (SGHC) Limited",    "SGI": "Somnigroup International Inc.",
    "SGML": "Sigma Lithium Corporation Common Shares",    "SGRY": "Surgery Partners Inc.",    "SHAK": "Shake Shack Inc.",    "SHAZ": "SharonAI Holdings Inc.",
    "SHC": "Sotera Health Company",    "SHEN": "Shenandoah Telecommunications Co",    "SHLS": "Shoals Technologies Group Inc.",    "SHO": "Sunstone Hotel Investors Inc. Sunstone H",
    "SHOO": "Steven Madden Ltd.",    "SHOP": "Shopify Inc.",    "SHW": "Sherwin-Williams Company (The)",    "SIBN": "SI-BONE Inc.",
    "SIG": "Signet Jewelers Limited Common Shares",    "SIGI": "Selective Insurance Group Inc.",    "SION": "Sionna Therapeutics Inc.",    "SIRI": "SiriusXM Holdings Inc.",
    "SITE": "SiteOne Landscape Supply Inc.",    "SJM": "The J.M. Smucker Company",    "SKE": "Skeena Resources Limited Common Shares",    "SKM": "SK Telecom Co. Ltd.",
    "SKT": "Tanger Inc.",    "SKWD": "Skyward Specialty Insurance Group Inc.",    "SKY": "Champion Homes Inc.",    "SKYT": "SkyWater Technology Inc.",
    "SKYW": "SkyWest Inc.",    "SLAB": "Silicon Laboratories Inc.",    "SLB": "SLB Limited Common Shares",    "SLDB": "Solid Biosciences Inc.",
    "SLDE": "Slide Insurance Holdings Inc.",    "SLG": "SL Green Realty Corp",    "SLGN": "Silgan Holdings Inc.",    "SLM": "SLM Corporation",
    "SLRC": "SLR Investment Corp.",    "SLS": "SELLAS Life Sciences Group Inc.",    "SLVM": "Sylvamo Corporation",    "SM": "SM Energy Company",
    "SMA": "SmartStop Self Storage REIT Inc.",    "SMCI": "Super Micro Computer Inc.",    "SMG": "Scotts Miracle-Gro Company (The)",    "SMMT": "Summit Therapeutics Inc.",
    "SMPL": "The Simply Good Foods Company",    "SMR": "NuScale Power Corporation",    "SMTC": "Semtech Corporation",    "SN": "SharkNinja Inc.",
    "SNA": "Snap-On Incorporated",    "SNDA": "Sonida Senior Living Inc.",    "SNDK": "Sandisk Corporation",    "SNDR": "Schneider National Inc.",
    "SNDX": "Syndax Pharmaceuticals Inc.",    "SNEX": "StoneX Group Inc.",    "SNN": "Smith & Nephew SNATS Inc.",    "SNOW": "Snowflake Inc.",
    "SNPS": "Synopsys Inc.",    "SNX": "TD SYNNEX Corporation",    "SNY": "Sanofi ADS",    "SO": "Southern Company (The)",
    "SOBO": "South Bow Corporation Common Shares",    "SOFI": "SoFi Technologies Inc.",    "SOLS": "Solstice Advanced Materials Inc.",    "SOLV": "Solventum Corporation",
    "SON": "Sonoco Products Company",    "SONO": "Sonos Inc.",    "SPB": "Spectrum Brands Holdings Inc.",    "SPCX": "Space Exploration Technologies Corp.",
    "SPG": "Simon Property Group Inc.",    "SPGI": "S&P Global Inc.",    "SPHR": "Sphere Entertainment Co.",    "SPIR": "Spire Global Inc.",
    "SPNT": "SiriusPoint Ltd. Common Shares",    "SPOT": "Spotify Technology S.A.",    "SPSC": "SPS Commerce Inc.",    "SPXC": "SPX Technologies Inc.",
    "SQM": "Sociedad Quimica y Minera S.A.",    "SR": "Spire Inc.",    "SRAD": "Sportradar Group AG",    "SRE": "DBA Sempra",
    "SRPT": "Sarepta Therapeutics Inc. Common Stock (",    "SRRK": "Scholar Rock Holding Corporation",    "SSB": "SouthState Bank Corporation",    "SSD": "Simpson Manufacturing Company Inc.",
    "SSNC": "SS&C Technologies Holdings Inc.",    "SSRM": "SSR Mining Inc.",    "ST": "Sensata Technologies Holding plc",    "STAA": "STAAR Surgical Company",
    "STAG": "Stag Industrial Inc.",    "STE": "STERIS plc (Ireland)",    "STEP": "StepStone Group Inc.",    "STLD": "Steel Dynamics Inc.",
    "STM": "STMicroelectronics N.V.",    "STNE": "StoneCo Ltd.",    "STNG": "Scorpio Tankers Inc. Common Shares",    "STOK": "Stoke Therapeutics Inc.",
    "STRL": "Sterling Infrastructure Inc.",    "STRO": "Sutro Biopharma Inc.",    "STT": "State Street Corporation",    "STUB": "StubHub Holdings Inc.",
    "STX": "Seagate Technology Holdings PLC",    "STZ": "Constellation Brands Inc.",    "SU": "Suncor Energy  Inc.",    "SUI": "Sun Communities Inc.",
    "SUNB": "Sunbelt Rentals Holdings Inc.",    "SUPN": "Supernus Pharmaceuticals Inc.",    "SVM": "Silvercorp Metals Inc. Common Shares",    "SVV": "Savers Value Village Inc.",
    "SW": "Smurfit WestRock plc",    "SWBI": "Smith & Wesson Brands Inc.",    "SWK": "Stanley Black & Decker Inc.",    "SWKS": "Skyworks Solutions Inc.",
    "SWX": "Southwest Gas Holdings Inc. Common Stock",    "SYF": "Synchrony Financial",    "SYK": "Stryker Corporation",    "SYM": "Symbotic Inc.",
    "SYNA": "Synaptics Incorporated Common Stock $0.0",    "SYRE": "Spyre Therapeutics Inc.",    "SYY": "Sysco Corporation",    "T": "AT&T Inc.",
    "TAC": "TransAlta Corporation",    "TALO": "Talos Energy Inc.",    "TAP": "Molson Coors Beverage Company",    "TARS": "Tarsus Pharmaceuticals Inc.",
    "TBBB": "BBB Foods Inc.",    "TBBK": "The Bancorp Inc",    "TBPH": "Theravance Biopharma Inc.",    "TCBI": "Texas Capital Bancshares Inc.",
    "TD": "Toronto Dominion Bank (The)",    "TDC": "Teradata Corporation",    "TDG": "Transdigm Group Incorporated",    "TDS": "Telephone and Data Systems Inc. Common S",
    "TDW": "Tidewater Inc.",    "TDY": "Teledyne Technologies Incorporated",    "TEAM": "Atlassian Corporation",    "TECH": "Bio-Techne Corp",
    "TECK": "Teck Resources Ltd",    "TEL": "TE Connectivity plc",    "TEM": "Tempus AI Inc.",    "TENB": "Tenable Holdings Inc.",
    "TER": "Teradyne Inc.",    "TEX": "Terex Corporation",    "TFC": "Truist Financial Corporation",    "TFPM": "Triple Flag Precious Metals Corp. Common",
    "TFSL": "TFS Financial Corporation",    "TFX": "Teleflex Incorporated",    "TGS": "Transportadora de Gas del Sur SA TGS",    "TGT": "Target Corporation",
    "TGTX": "TG Therapeutics Inc.",    "TH": "Target Hospitality Corp.",    "THC": "Tenet Healthcare Corporation",    "THO": "Thor Industries Inc.",
    "TIGO": "Millicom International Cellular S.A.",    "TILE": "Interface Inc.",    "TJX": "TJX Companies Inc. (The)",    "TKO": "TKO Group Holdings Inc.",
    "TKR": "Timken Company (The)",    "TLK": "PT Telekomunikasi Indonesia Tbk",    "TLN": "Talen Energy Corporation",    "TM": "Toyota Motor Corporation",
    "TMDX": "TransMedics Group Inc.",    "TMHC": "Taylor Morrison Home Corporation",    "TMO": "Thermo Fisher Scientific Inc",    "TMUS": "T-Mobile US Inc.",
    "TNDM": "Tandem Diabetes Care Inc.",    "TNET": "TriNet Group Inc.",    "TNGX": "Tango Therapeutics Inc.",    "TNK": "Teekay Tankers Ltd.",
    "TNL": "Travel   Leisure Co. Common  Stock",    "TOL": "Toll Brothers Inc.",    "TOST": "Toast Inc.",    "TOWN": "TowneBank",
    "TPB": "Turning Point Brands Inc.",    "TPC": "Tutor Perini Corporation",    "TPG": "TPG Inc.",    "TPL": "Texas Pacific Land Corporation",
    "TPR": "Tapestry Inc.",    "TRAX": "First Tracks Biotherapeutics Inc.",    "TREE": "LendingTree Inc.",    "TREX": "Trex Company Inc.",
    "TRGP": "Targa Resources Inc.",    "TRI": "Thomson Reuters Corporation Common Share",    "TRIN": "Trinity Capital Inc.",    "TRIP": "TripAdvisor Inc.",
    "TRMB": "Trimble Inc.",    "TRMD": "TORM plc",    "TRMK": "Trustmark Corporation",    "TRN": "Trinity Industries Inc.",
    "TRNO": "Terreno Realty Corporation",    "TROW": "T. Rowe Price Group Inc.",    "TRP": "TC Energy Corporation",    "TRS": "TriMas Corporation",
    "TRU": "TransUnion",    "TRUP": "Trupanion Inc.",    "TRV": "The Travelers Companies Inc.",    "TRVI": "Trevi Therapeutics Inc.",
    "TSCO": "Tractor Supply Company",    "TSEM": "Tower Semiconductor Ltd.",    "TSLA": "Tesla Inc.",    "TSLX": "Sixth Street Specialty Lending Inc.",
    "TSM": "Taiwan Semiconductor Manufacturing Compa",    "TSN": "Tyson Foods Inc.",    "TT": "Trane Technologies plc",    "TTAN": "ServiceTitan Inc.",
    "TTC": "Toro Company (The)",    "TTD": "The Trade Desk Inc.",    "TTE": "TotalEnergies SE",    "TTEK": "Tetra Tech Inc.",
    "TTI": "Tetra Technologies Inc.",    "TTMI": "TTM Technologies Inc.",    "TTWO": "Take-Two Interactive Software Inc.",    "TU": "Telus Corporation",
    "TVTX": "Travere Therapeutics Inc.",    "TW": "Tradeweb Markets Inc.",    "TWLO": "Twilio Inc.",    "TWO": "Two Harbors Investment Corp",
    "TWST": "Twist Bioscience Corporation",    "TXG": "10x Genomics Inc.",    "TXN": "Texas Instruments Incorporated",    "TXNM": "TXNM Energy Inc.",
    "TXRH": "Texas Roadhouse Inc.",    "TXT": "Textron Inc.",    "TYL": "Tyler Technologies Inc.",    "TYRA": "Tyra Biosciences Inc.",
    "U": "Unity Software Inc.",    "UAL": "United Airlines Holdings Inc.",    "UBER": "Uber Technologies Inc.",    "UBS": "UBS Group AG Registered",
    "UBSI": "United Bankshares Inc.",    "UCB": "United Community Banks Inc.",    "UCTT": "Ultra Clean Holdings Inc.",    "UDR": "UDR Inc.",
    "UE": "Urban Edge Properties Common Shares of B",    "UEC": "Uranium Energy Corp.",    "UFPI": "UFP Industries Inc.",    "UGI": "UGI Corporation",
    "UHS": "Universal Health Services Inc.",    "ULS": "UL Solutions Inc.",    "ULTA": "Ulta Beauty Inc.",    "UMAC": "Unusual Machines Inc.",
    "UMBF": "UMB Financial Corporation",    "UMC": "United Microelectronics Corporation (NEW",    "UMH": "UMH Properties Inc.",    "UNFI": "United Natural Foods Inc.",
    "UNH": "UnitedHealth Group Incorporated Common S",    "UNIT": "Uniti Group Inc.",    "UNM": "Unum Group",    "UNP": "Union Pacific Corporation",
    "UPBD": "Upbound Group Inc.",    "UPS": "United Parcel Service Inc.",    "UPST": "Upstart Holdings Inc. Common stock",    "URBN": "Urban Outfitters Inc.",
    "URGN": "UroGen Pharma Ltd.",    "URI": "United Rentals Inc.",    "USAR": "USA Rare Earth Inc.",    "USB": "U.S. Bancorp",
    "USFD": "US Foods Holding Corp.",    "UTHR": "United Therapeutics Corporation",    "UTI": "Universal Technical Institute Inc",    "UUUU": "Energy Fuels Inc",
    "V": "Visa Inc.",    "VAC": "Marriott Vacations Worldwide Corporation",    "VAL": "Valaris Limited Common Shares",    "VC": "Visteon Corporation",
    "VCEL": "Vericel Corporation",    "VCTR": "Victory Capital Holdings Inc.",    "VCYT": "Veracyte Inc.",    "VECO": "Veeco Instruments Inc.",
    "VEEV": "Veeva Systems Inc.",    "VERA": "Vera Therapeutics Inc.",    "VERX": "Vertex Inc.",    "VFC": "V.F. Corporation",
    "VG": "Venture Global Inc.",    "VGNT": "Versigent PLC",    "VIA": "Via Transportation Inc.",    "VIAV": "Viavi Solutions Inc.",
    "VICI": "VICI Properties Inc.",    "VICR": "Vicor Corporation",    "VIK": "Viking Holdings Ltd",    "VIRT": "Virtu Financial Inc.",
    "VISN": "Vistance Networks Inc.",    "VITL": "Vital Farms Inc.",    "VKTX": "Viking Therapeutics Inc.",    "VLO": "Valero Energy Corporation",
    "VLTO": "Veralto Corp",    "VLY": "Valley National Bancorp",    "VMC": "Vulcan Materials Company (Holding Compan",    "VNOM": "Viper Energy Inc.",
    "VNT": "Vontier Corporation",    "VOR": "Vor Biopharma Inc.",    "VOYA": "Voya Financial Inc.",    "VOYG": "Voyager Technologies Inc.",
    "VPG": "Vishay Precision Group Inc.",    "VRDN": "Viridian Therapeutics Inc.",    "VRNS": "Varonis Systems Inc.",    "VRSK": "Verisk Analytics Inc.",
    "VRSN": "VeriSign Inc.",    "VRT": "Vertiv Holdings LLC",    "VRTX": "Vertex Pharmaceuticals Incorporated",    "VSAT": "ViaSat Inc.",
    "VSEC": "VSE Corporation",    "VSH": "Vishay Intertechnology Inc.",    "VSNT": "Versant Media Group Inc.",    "VST": "Vistra Corp.",
    "VSTS": "Vestis Corporation",    "VSXY": "Victorias Secret & Co.",    "VTR": "Ventas Inc.",    "VTRS": "Viatris Inc.",
    "VTS": "Vitesse Energy Inc.",    "VVV": "Valvoline Inc.",    "VVX": "V2X Inc.",    "VZ": "Verizon Communications Inc.",
    "W": "Wayfair Inc.",    "WAB": "Westinghouse Air Brake Technologies Corp",    "WABC": "Westamerica Bancorporation",    "WAFD": "WaFd Inc.",
    "WAL": "Western Alliance Bancorporation Common S",    "WAT": "Waters Corporation",    "WAY": "Waystar Holding Corp.",    "WBD": "Warner Bros. Discovery Inc. Series A",
    "WBI": "WaterBridge Infrastructure LLC",    "WBS": "Webster Financial Corporation",    "WCC": "WESCO International Inc.",    "WCN": "Waste Connections Inc. Common Shares",
    "WDAY": "Workday Inc.",    "WDC": "Western Digital Corporation",    "WEC": "WEC Energy Group Inc.",    "WELL": "Welltower Inc.",
    "WERN": "Werner Enterprises Inc.",    "WEX": "WEX Inc. common stock",    "WFC": "Wells Fargo & Company",    "WFRD": "Weatherford International plc",
    "WGO": "Winnebago Industries Inc.",    "WGS": "GeneDx Holdings Corp.",    "WH": "Wyndham Hotels & Resorts Inc.",    "WHD": "Cactus Inc.",
    "WHR": "Whirlpool Corporation",    "WING": "Wingstop Inc.",    "WIX": "Wix.com Ltd.",    "WK": "Workiva Inc.",
    "WKC": "World Kinect Corporation",    "WLDN": "Willdan Group Inc.",    "WLK": "Westlake Corporation",    "WLY": "John Wiley & Sons Inc.",
    "WM": "Waste Management Inc.",    "WMB": "Williams Companies Inc. (The)",    "WMG": "Warner Music Group Corp.",    "WMS": "Advanced Drainage Systems Inc.",
    "WMT": "Walmart Inc.",    "WNC": "Wabash National Corporation",    "WOLF": "Wolfspeed Inc. Common Stock New",    "WOR": "Worthington Enterprises Inc. Common Shar",
    "WPC": "W. P. Carey Inc. REIT",    "WPM": "Wheaton Precious Metals Corp Common Shar",    "WRB": "W.R. Berkley Corporation",    "WRBY": "Warby Parker Inc.",
    "WS": "Worthington Steel Inc. Common Shares",    "WSBC": "WesBanco Inc.",    "WSC": "WillScot Holdings Corporation",    "WSE": "Wise Group plc",
    "WSFS": "WSFS Financial Corporation",    "WSM": "Williams-Sonoma Inc. Common Stock (DE)",    "WSO": "Watsco Inc.",    "WSR": "Whitestone REIT Common Shares",
    "WST": "West Pharmaceutical Services Inc.",    "WT": "WisdomTree Inc.",    "WTFC": "Wintrust Financial Corporation",    "WTRG": "Essential Utilities Inc.",
    "WTS": "Watts Water Technologies Inc.",    "WTTR": "Select Water Solutions Inc.",    "WTW": "Willis Towers Watson Public Limited Comp",    "WULF": "TeraWulf Inc.",
    "WWD": "Woodward Inc.",    "WWW": "Wolverine World Wide Inc.",    "WY": "Weyerhaeuser Company",    "WYFI": "WhiteFiber Inc.",
    "WYNN": "Wynn Resorts Limited Common stock",    "XE": "X-Energy Inc.",    "XEL": "Xcel Energy Inc.",    "XENE": "Xenon Pharmaceuticals Inc. Common Shares",
    "XHR": "Xenia Hotels & Resorts Inc.",    "XMTR": "Xometry Inc.",    "XNCR": "Xencor Inc.",    "XNDU": "Xanadu Quantum Technologies Limited",
    "XOM": "Exxon Mobil Corporation",    "XP": "XP Inc.",    "XPO": "XPO Inc.",    "XPRO": "Expro Group Holdings N.V.",
    "XRAY": "DENTSPLY SIRONA Inc.",    "XYL": "Xylem Inc. Common Stock New",    "XYZ": "Block Inc.",    "YELP": "Yelp Inc.",
    "YETI": "YETI Holdings Inc.",    "YOU": "Clear Secure Inc.",    "YPF": "YPF Sociedad Anonima",    "YSS": "York Space Systems Inc.",
    "YSWY": "Yesway Inc.",    "YUM": "Yum! Brands Inc.",    "YUMC": "Yum China Holdings Inc.",    "Z": "Zillow Group Inc.",
    "ZBH": "Zimmer Biomet Holdings Inc.",    "ZBIO": "Zenas BioPharma Inc.",    "ZBRA": "Zebra Technologies Corporation",    "ZD": "Ziff Davis Inc.",
    "ZETA": "Zeta Global Holdings Corp.",    "ZG": "Zillow Group Inc.",    "ZGN": "Ermenegildo Zegna N.V.",    "ZIM": "ZIM Integrated Shipping Services Ltd.",
    "ZION": "Zions Bancorporation N.A.",    "ZM": "Zoom Communications Inc.",    "ZS": "Zscaler Inc.",    "ZSQR": "Z Squared Inc.",
    "ZTS": "Zoetis Inc.",    "ZVRA": "Zevra Therapeutics Inc.",    "ZWS": "Zurn Elkay Water Solutions Corporation",    "ZYME": "Zymeworks Inc.",
}