"""
미국 자동 확장 유니버스 — 나스닥+NYSE 성장섹터(시총 1B+) 자동 선별.
생성일: 2026-06-26 | 출처: rreichel3/US-Stock-Symbols (github)
성장섹터(Tech/Health/Telecom/ConsumerDisc/Energy) 시총 10억달러 이상.
거래대금 동적 필터(scanner)로 실제 스캔 시 저거래 종목은 추가 제외됨.
총 1292개. SLS 같은 중소형 모멘텀주 포함.
"""

US_UNIVERSE_AUTO = {
    "NVDA": "NVIDIA Corporation",    "GOOGL": "Alphabet Inc",    "GOOG": "Alphabet Inc. Class C Capita",    "AAPL": "Apple Inc",
    "MSFT": "Microsoft Corporation",    "AMZN": "Amazon.com Inc",    "TSM": "Taiwan Semiconductor Manufac",    "SPCX": "Space Exploration Technologi",
    "AVGO": "Broadcom Inc",    "META": "Meta Platforms Inc",    "MU": "Micron Technology Inc",    "LLY": "Eli Lilly and Company",
    "WMT": "Walmart Inc",    "AMD": "Advanced Micro Devices Inc",    "ASML": "ASML Holding N.V. New York R",    "INTC": "Intel Corporation",
    "V": "Visa Inc",    "JNJ": "Johnson & Johnson",    "AZN": "AstraZeneca PLC",    "XOM": "Exxon Mobil Corporation",
    "AMAT": "Applied Materials Inc",    "LRCX": "Lam Research Corporation",    "CSCO": "Cisco Systems Inc. (DE)",    "ORCL": "Oracle Corporation",
    "MA": "Mastercard Incorporated",    "ABBV": "AbbVie Inc",    "COST": "Costco Wholesale Corporation",    "GE": "GE Aerospace",
    "PG": "Procter & Gamble Company (Th",    "SNDK": "Sandisk Corporation",    "HD": "Home Depot Inc. (The)",    "CVX": "Chevron Corporation",
    "KLAC": "KLA Corporation",    "MRK": "Merck & Company Inc. (new)",    "NFLX": "Netflix Inc",    "NVS": "Novartis AG",
    "TXN": "Texas Instruments Incorporat",    "PM": "Philip Morris International ",    "DELL": "Dell Technologies Inc. Class",    "PLTR": "Palantir Technologies Inc",
    "MRVL": "Marvell Technology Inc",    "IBM": "International Business Machi",    "PANW": "Palo Alto Networks Inc",    "CCZ": "Comcast Holdings ZONES",
    "WDC": "Western Digital Corporation",    "STX": "Seagate Technology Holdings ",    "QCOM": "QUALCOMM Incorporated",    "NVO": "Novo Nordisk A/S",
    "ANET": "Arista Networks Inc",    "ADI": "Analog Devices Inc",    "APH": "Amphenol Corporation",    "TMUS": "T-Mobile US Inc",
    "VZ": "Verizon Communications Inc",    "AMGN": "Amgen Inc",    "MCD": "McDonald's Corporation",    "NEE": "NextEra Energy Inc",
    "SAP": "SAP  SE ADS",    "CRWD": "CrowdStrike Holdings Inc",    "TJX": "TJX Companies Inc. (The)",    "TTE": "TotalEnergies SE",
    "DIS": "Walt Disney Company (The)",    "ETN": "Eaton Corporation PLC",    "ABT": "Abbott Laboratories",    "T": "AT&T Inc",
    "GILD": "Gilead Sciences Inc",    "APP": "Applovin Corporation",    "UBER": "Uber Technologies Inc",    "TBB": "AT&T Inc. 5.350% Global Note",
    "SHOP": "Shopify Inc. Subordinate Vot",    "ISRG": "Intuitive Surgical Inc",    "BKNG": "Booking Holdings Inc",    "BTI": "British American Tobacco  In",
    "PFE": "Pfizer Inc",    "COP": "ConocoPhillips",    "VRT": "Vertiv Holdings LLC",    "LOW": "Lowe's Companies Inc",
    "CRM": "Salesforce Inc",    "ENB": "Enbridge Inc",    "MO": "Altria Group Inc",    "VRTX": "Vertex Pharmaceuticals Incor",
    "SYK": "Stryker Corporation",    "SBUX": "Starbucks Corporation",    "BMY": "Bristol-Myers Squibb Company",    "FTNT": "Fortinet Inc",
    "PBR": "Petroleo Brasileiro S.A. Pet",    "MDT": "Medtronic plc",    "SNY": "Sanofi ADS",    "CDNS": "Cadence Design Systems Inc",
    "MAR": "Marriott International",    "BP": "BP p.l.c",    "NOW": "ServiceNow Inc",    "MCK": "McKesson Corporation",
    "SPOT": "Spotify Technology S.A",    "BE": "Bloom Energy Corporation",    "MMM": "3M Company",    "SNPS": "Synopsys Inc",
    "RCL": "Royal Caribbean Cruises Ltd",    "HCA": "HCA Healthcare Inc",    "ABNB": "Airbnb Inc",    "ELV": "Elevance Health Inc",
    "ACN": "Accenture plc (Ireland)",    "SHW": "Sherwin-Williams Company (Th",    "CNQ": "Canadian Natural Resources L",    "MELI": "MercadoLibre Inc",
    "EMR": "Emerson Electric Company",    "CMCSA": "Comcast Corporation",    "NET": "Cloudflare Inc",    "COHR": "Coherent Corp",
    "ECL": "Ecolab Inc",    "EQNR": "Equinor ASA",    "SNOW": "Snowflake Inc",    "DDOG": "Datadog Inc",
    "FDX": "FedEx Corporation",    "HLT": "Hilton Worldwide Holdings In",    "DASH": "DoorDash Inc",    "ADBE": "Adobe Inc",
    "VLO": "Valero Energy Corporation",    "NXPI": "NXP Semiconductors N.V",    "CI": "The Cigna Group",    "MPC": "Marathon Petroleum Corporati",
    "E": "ENI S.p.A",    "BAM": "Brookfield Asset Management ",    "CL": "Colgate-Palmolive Company",    "CVNA": "Carvana Co",
    "ORLY": "O'Reilly Automotive Inc",    "EOG": "EOG Resources Inc",    "SLB": "SLB Limited Common Shares",    "MPWR": "Monolithic Power Systems Inc",
    "INTU": "Intuit Inc",    "ROST": "Ross Stores Inc",    "PSX": "Phillips 66",    "ALAB": "Astera Labs Inc",
    "WBD": "Warner Bros. Discovery Inc. ",    "LITE": "Lumentum Holdings Inc",    "STM": "STMicroelectronics N.V",    "MSI": "Motorola Solutions Inc",
    "BSX": "Boston Scientific Corporatio",    "NBIS": "Nebius Group N.V",    "REGN": "Regeneron Pharmaceuticals In",    "SU": "Suncor Energy  Inc",
    "PCAR": "PACCAR Inc",    "TGT": "Target Corporation",    "HPE": "Hewlett Packard Enterprise C",    "NKE": "Nike Inc",
    "DAL": "Delta Air Lines Inc",    "FLEX": "Flex Ltd",    "TEL": "TE Connectivity plc",    "BKR": "Baker Hughes Company",
    "COR": "Cencora Inc",    "CAH": "Cardinal Health Inc",    "CRWV": "CoreWeave Inc",    "FAST": "Fastenal Company",
    "EW": "Edwards Lifesciences Corpora",    "FANG": "Diamondback Energy Inc",    "EA": "Electronic Arts Inc",    "MCHP": "Microchip Technology Incorpo",
    "OXY": "Occidental Petroleum Corpora",    "CRDO": "Credo Technology Group Holdi",    "AZO": "AutoZone Inc",    "MDLN": "Medline Inc",
    "DVN": "Devon Energy Corporation",    "EBAY": "eBay Inc",    "GFS": "GlobalFoundries Inc",    "DHI": "D.R. Horton Inc",
    "ON": "ON Semiconductor Corporation",    "CVE": "Cenovus Energy Inc",    "VIK": "Viking Holdings Ltd",    "HUM": "Humana Inc",
    "TTWO": "Take-Two Interactive Softwar",    "XYZ": "Block Inc",    "IDXX": "IDEXX Laboratories Inc",    "BDX": "Becton Dickinson and Company",
    "YUM": "Yum! Brands Inc",    "CLS": "Celestica Inc",    "CMG": "Chipotle Mexican Grill Inc",    "LYV": "Live Nation Entertainment In",
    "CCL": "Carnival Corporation Ltd. Co",    "ADSK": "Autodesk Inc",    "MSCI": "MSCI Inc",    "JBL": "Jabil Inc",
    "ALNY": "Alnylam Pharmaceuticals Inc",    "TKO": "TKO Group Holdings Inc",    "SYY": "Sysco Corporation",    "RVMD": "Revolution Medicines Inc",
    "NTRA": "Natera Inc",    "KVUE": "Kenvue Inc",    "CBRS": "Cerebras Systems Inc",    "KMB": "Kimberly-Clark Corporation",
    "BIDU": "Baidu Inc. ADS",    "TRI": "Thomson Reuters Corporation ",    "Q": "Qnity Electronics Inc",    "CHT": "Chunghwa Telecom Co. Ltd",
    "ALC": "Alcon Inc",    "ROP": "Roper Technologies Inc",    "QSR": "Restaurant Brands Internatio",    "RBLX": "Roblox Corporation",
    "UI": "Ubiquiti Inc",    "ZTS": "Zoetis Inc",    "EQT": "EQT Corporation",    "CNC": "Centene Corporation",
    "RPRX": "Royalty Pharma plc",    "IQV": "IQVIA Holdings Inc",    "SUNB": "Sunbelt Rentals Holdings Inc",    "LVS": "Las Vegas Sands Corp",
    "CPNG": "Coupang Inc",    "TSEM": "Tower Semiconductor Ltd",    "RDDT": "Reddit Inc",    "NTAP": "NetApp Inc",
    "EXPE": "Expedia Group Inc",    "MSTR": "Strategy Inc",    "BIIB": "Biogen Inc",    "MTSI": "MACOM Technology Solutions H",
    "GEHC": "GE HealthCare Technologies I",    "TPR": "Tapestry Inc",    "EL": "Estee Lauder Companies Inc. ",    "CASY": "Casey's General Stores Inc",
    "TWLO": "Twilio Inc",    "HAL": "Halliburton Company",    "RMD": "ResMed Inc",    "INIO": "INNIO N.V",
    "CW": "Curtiss-Wright Corporation",    "HUBB": "Hubbell Inc",    "WSM": "Williams-Sonoma Inc. (DE)",    "OTIS": "Otis Worldwide Corporation",
    "ECHO": "EchoStar  Corporation",    "WDAY": "Workday Inc",    "CPRT": "Copart Inc. (DE)",    "PBA": "Pembina Pipeline Corp. (Cana",
    "PPG": "PPG Industries Inc",    "TPL": "Texas Pacific Land Corporati",    "ILMN": "Illumina Inc",    "AER": "AerCap Holdings N.V",
    "PHG": "Koninklijke Philips N.V. NY ",    "FTI": "TechnipFMC plc Ordinary Shar",    "FSLR": "First Solar Inc",    "FICO": "Fair Isaac Corporation",
    "DXCM": "DexCom Inc",    "WWD": "Woodward Inc",    "DG": "Dollar General Corporation",    "PHM": "PulteGroup Inc",
    "VEEV": "Veeva Systems Inc",    "ASTS": "AST SpaceMobile Inc",    "LUV": "Southwest Airlines Company",    "FISV": "Fiserv Inc",
    "SW": "Smurfit WestRock plc",    "WST": "West Pharmaceutical Services",    "ROIV": "Roivant Sciences Ltd. Common",    "DRI": "Darden Restaurants Inc",
    "ZM": "Zoom Communications Inc",    "XPO": "XPO Inc",    "P": "Everpure Inc. common stock",    "MRNA": "Moderna Inc",
    "MDB": "MongoDB Inc",    "ONON": "On Holding AG",    "CHD": "Church & Dwight Company Inc",    "LEN": "Lennar Corporation",
    "WIT": "Wipro Limited",    "DGX": "Quest Diagnostics Incorporat",    "VRSN": "VeriSign Inc",    "DLTR": "Dollar Tree Inc",
    "INSM": "Insmed Incorporated",    "SNX": "TD SYNNEX Corporation",    "TTMI": "TTM Technologies Inc",    "LH": "Labcorp Holdings Inc",
    "FFIV": "F5 Inc",    "BCE": "BCE Inc",    "PKG": "Packaging Corporation of Ame",    "INCY": "Incyte Corp",
    "RBA": "RB Global Inc",    "CPAY": "Corpay Inc",    "DKS": "Dick's Sporting Goods Inc",    "AMKR": "Amkor Technology Inc",
    "USFD": "US Foods Holding Corp",    "EXE": "Expand Energy Corporation",    "HPQ": "HP Inc",    "OMC": "Omnicom Group Inc",
    "ULTA": "Ulta Beauty Inc",    "SNA": "Snap-On Incorporated",    "OKTA": "Okta Inc",    "ROL": "Rollins Inc",
    "STE": "STERIS plc (Ireland)",    "BURL": "Burlington Stores Inc",    "SN": "SharkNinja Inc",    "ZS": "Zscaler Inc",
    "ROKU": "Roku Inc",    "AMCR": "Amcor plc",    "LSCC": "Lattice Semiconductor Corpor",    "FIS": "Fidelity National Informatio",
    "ULS": "UL Solutions Inc",    "SMCI": "Super Micro Computer Inc",    "AS": "Amer Sports Inc",    "GH": "Guardant Health Inc",
    "TEAM": "Atlassian Corporation",    "FDXF": "FedEx Freight Holding Compan",    "IONQ": "IonQ Inc",    "RCI": "Rogers Communication Inc",
    "VTRS": "Viatris Inc",    "QNT": "Quantinuum Inc",    "GPN": "Global Payments Inc",    "CTSH": "Cognizant Technology Solutio",
    "H": "Hyatt Hotels Corporation",    "NVR": "NVR Inc",    "APG": "APi Group Corporation",    "CHTR": "Charter Communications Inc. ",
    "YPF": "YPF Sociedad Anonima",    "MGA": "Magna International Inc",    "FPS": "Forgent Power Solutions Inc",    "SITM": "SiTime Corporation",
    "ZBH": "Zimmer Biomet Holdings Inc",    "WCC": "WESCO International Inc",    "GNRC": "Generac Holdlings Inc",    "TU": "Telus Corporation",
    "IREN": "IREN Limited",    "NVMI": "Nova Ltd",    "IOT": "Samsara Inc",    "PFGC": "Performance Food Group Compa",
    "FLUT": "Flutter Entertainment plc",    "GMAB": "Genmab A/S ADS",    "WSO": "Watsco Inc",    "SGI": "Somnigroup International Inc",
    "NBIX": "Neurocrine Biosciences Inc",    "AKAM": "Akamai Technologies Inc",    "CDW": "CDW Corporation",    "ASND": "Ascendis Pharma A/S Ordinary",
    "BBY": "Best Buy Co. Inc",    "TSCO": "Tractor Supply Company",    "THC": "Tenet Healthcare Corporation",    "PR": "Permian Resources Corporatio",
    "BR": "Broadridge Financial Solutio",    "VNOM": "Viper Energy Inc",    "GPC": "Genuine Parts Company",    "NWS": "News Corporation",
    "SSNC": "SS&C Technologies Holdings I",    "DOCN": "DigitalOcean Holdings Inc",    "TOL": "Toll Brothers Inc",    "OVV": "Ovintiv Inc. (DE)",
    "RRX": "Regal Rexnord Corporation",    "SMTC": "Semtech Corporation",    "VICR": "Vicor Corporation",    "MOD": "Modine Manufacturing Company",
    "TOST": "Toast Inc",    "MEDP": "Medpace Holdings Inc",    "TIGO": "Millicom International Cellu",    "RBRK": "Rubrik Inc",
    "LOGI": "Logitech International S.A",    "ARMK": "Aramark",    "SWK": "Stanley Black & Decker Inc",    "AEIS": "Advanced Energy Industries I",
    "RPM": "RPM International Inc",    "BWA": "BorgWarner Inc",    "DECK": "Deckers Outdoor Corporation",    "JAZZ": "Jazz Pharmaceuticals plc (Ir",
    "GRAB": "Grab Holdings Limited",    "YUMC": "Yum China Holdings Inc",    "TLK": "PT Telekomunikasi Indonesia ",    "GEN": "Gen Digital Inc",
    "COO": "The Cooper Companies Inc",    "BTSG": "BrightSpring Health Services",    "WMG": "Warner Music Group Corp",    "NWSA": "News Corporation",
    "DVA": "DaVita Inc",    "BBIO": "BridgeBio Pharma Inc",    "SANM": "Sanmina Corporation",    "SOLV": "Solventum Corporation",
    "EXEL": "Exelixis Inc",    "RMBS": "Rambus Inc",    "GIB": "CGI Inc",    "APTV": "Aptiv PLC",
    "QXO": "QXO Inc",    "PTC": "PTC Inc",    "CHKP": "Check Point Software Technol",    "IONS": "Ionis Pharmaceuticals Inc",
    "WULF": "TeraWulf Inc",    "SKM": "SK Telecom Co. Ltd",    "SNN": "Smith & Nephew SNATS Inc",    "PAC": "Grupo Aeroportuario Del Paci",
    "RDY": "Dr. Reddy's Laboratories Ltd",    "AIT": "Applied Industrial Technolog",    "NTNX": "Nutanix Inc",    "AVY": "Avery Dennison Corporation",
    "ALGN": "Align Technology Inc",    "LDOS": "Leidos Holdings Inc",    "TXRH": "Texas Roadhouse Inc",    "PEN": "Penumbra Inc",
    "W": "Wayfair Inc",    "ICLR": "ICON plc",    "AUR": "Aurora Innovation Inc",    "DINO": "HF Sinclair Corporation",
    "AXSM": "Axsome Therapeutics Inc",    "ELAN": "Elanco Animal Health Incorpo",    "LULU": "lululemon athletica inc",    "PAG": "Penske Automotive Group Inc",
    "MGM": "MGM Resorts International",    "LFUS": "Littelfuse Inc",    "BLD": "TopBuild Corp",    "HAS": "Hasbro Inc",
    "WMS": "Advanced Drainage Systems In",    "TYL": "Tyler Technologies Inc",    "MDGL": "Madrigal Pharmaceuticals Inc",    "APA": "APA Corporation",
    "VIAV": "Viavi Solutions Inc",    "ALLE": "Allegion plc",    "DT": "Dynatrace Inc",    "ARW": "Arrow Electronics Inc",
    "APLD": "Applied Digital Corporation",    "BROS": "Dutch Bros Inc",    "AAL": "American Airlines Group Inc",    "FORM": "FormFactor Inc. FormFactor I",
    "CLX": "Clorox Company (The)",    "GMED": "Globus Medical Inc",    "DKNG": "DraftKings Inc",    "POWL": "Powell Industries Inc",
    "MOH": "Molina Healthcare Inc",    "ALGM": "Allegro MicroSystems Inc",    "ARWR": "Arrowhead Pharmaceuticals In",    "BAX": "Baxter International Inc",
    "AAOI": "Applied Optoelectronics Inc",    "NYT": "New York Times Company (The)",    "BMRN": "BioMarin Pharmaceutical Inc",    "TECH": "Bio-Techne Corp",
    "BJ": "BJ's Wholesale Club Holdings",    "SMMT": "Summit Therapeutics Inc",    "CART": "Maplebear Inc",    "PINS": "Pinterest Inc",
    "AYI": "Acuity Inc",    "AR": "Antero Resources Corporation",    "PODD": "Insulet Corporation",    "KRYS": "Krystal Biotech Inc",
    "AGX": "Argan Inc",    "SWKS": "Skyworks Solutions Inc",    "GDDY": "GoDaddy Inc",    "R": "Ryder System Inc",
    "ALSN": "Allison Transmission Holding",    "FIVE": "Five Below Inc",    "WYNN": "Wynn Resorts Limited Common ",    "GSAT": "Globalstar Inc",
    "CRL": "Charles River Laboratories I",    "CYTK": "Cytokinetics Incorporated",    "SCI": "Service Corporation Internat",    "APGE": "Apogee Therapeutics Inc",
    "GIL": "Gildan Activewear Inc. Sub. ",    "EHC": "Encompass Health Corporation",    "TEM": "Tempus AI Inc",    "CACI": "CACI International Inc",
    "NUVL": "Nuvalent Inc",    "CAVA": "CAVA Group Inc",    "ENSG": "The Ensign Group Inc",    "MUSA": "Murphy USA Inc",
    "NCLH": "Norwegian Cruise Line Holdin",    "PSO": "Pearson Plc",    "KYMR": "Kymera Therapeutics Inc",    "FROG": "JFrog Ltd",
    "BLDR": "Builders FirstSource Inc",    "HSIC": "Henry Schein Inc",    "FCFS": "FirstCash Holdings Inc",    "DPZ": "Domino's Pizza Inc",
    "PL": "Planet Labs PBC",    "GME": "GameStop Corporation",    "LLYVK": "Liberty Live Holdings Inc. S",    "SIRI": "SiriusXM Holdings Inc",
    "CNM": "Core & Main Inc",    "ASR": "Grupo Aeroportuario del Sure",    "TTC": "Toro Company (The)",    "LEVI": "Levi Strauss & Co",
    "ESE": "ESCO Technologies Inc",    "GWRE": "Guidewire Software Inc",    "JKHY": "Jack Henry & Associates Inc",    "PRAX": "Praxis Precision Medicines I",
    "MSGS": "Madison Square Garden Sports",    "PAYP": "PayPay Corporation American ",    "CORT": "Corcept Therapeutics Incorpo",    "DDS": "Dillard's Inc",
    "ALV": "Autoliv Inc",    "LLYVA": "Liberty Live Holdings Inc. S",    "ACM": "AECOM",    "FIG": "Figma Inc",
    "LTH": "Life Time Group Holdings Inc",    "ALKS": "Alkermes plc",    "LGN": "Legence Corp. Common stock",    "UHS": "Universal Health Services In",
    "BSY": "Bentley Systems Incorporated",    "HUBS": "HubSpot Inc",    "OSCR": "Oscar Health Inc",    "SSD": "Simpson Manufacturing Compan",
    "HALO": "Halozyme Therapeutics Inc",    "KT": "KT Corporation",    "LUMN": "Lumen Technologies Inc",    "FRO": "Frontline Plc",
    "RRC": "Range Resources Corporation",    "IT": "Gartner Inc",    "MXL": "MaxLinear Inc",    "AOS": "A.O. Smith Corporation",
    "QRVO": "Qorvo Inc",    "GKOS": "Glaukos Corporation",    "ECG": "Everus Construction Group In",    "ENS": "EnerSys",
    "COMP": "Compass Inc",    "TGTX": "TG Therapeutics Inc",    "VSAT": "ViaSat Inc",    "RGEN": "Repligen Corporation",
    "BIRK": "Birkenstock Holding plc",    "IBRX": "ImmunityBio Inc",    "VSH": "Vishay Intertechnology Inc",    "MTCH": "Match Group Inc",
    "TTD": "The Trade Desk Inc",    "DOCU": "DocuSign Inc",    "QBTS": "D-Wave Quantum Inc. Common S",    "QGEN": "Qiagen N.V. Common Shares",
    "PLXS": "Plexus Corp",    "PTGX": "Protagonist Therapeutics Inc",    "IMVT": "Immunovant Inc",    "CAMT": "Camtek Ltd",
    "CRUS": "Cirrus Logic Inc",    "STN": "Stantec Inc",    "PCVX": "Vaxcyte Inc",    "SYRE": "Spyre Therapeutics Inc",
    "SOBO": "South Bow Corporation Common",    "FDS": "FactSet Research Systems Inc",    "HIMS": "Hims & Hers Health Inc",    "MANH": "Manhattan Associates Inc",
    "POOL": "Pool Corporation",    "KMX": "CarMax Inc",    "AVT": "Avnet Inc",    "EAT": "Brinker International Inc",
    "AXTA": "Axalta Coating Systems Ltd. ",    "CHWY": "Chewy Inc",    "RYTM": "Rhythm Pharmaceuticals Inc",    "KEX": "Kirby Corporation",
    "TTEK": "Tetra Tech Inc",    "MHK": "Mohawk Industries Inc",    "ETSY": "Etsy Inc",    "GAP": "Gap Inc. (The)",
    "SAIL": "SailPoint Inc",    "SNAP": "Snap Inc",    "SLAB": "Silicon Laboratories Inc",    "MIRM": "Mirum Pharmaceuticals Inc",
    "BAH": "Booz Allen Hamilton Holding ",    "YOU": "Clear Secure Inc",    "LNTH": "Lantheus Holdings Inc",    "ACMR": "ACM Research Inc",
    "RSI": "Rush Street Interactive Inc",    "PTCT": "PTC Therapeutics Inc",    "HQY": "HealthEquity Inc",    "LEA": "Lear Corporation",
    "KLIC": "Kulicke and Soffa Industries",    "LQDA": "Liquidia Corporation",    "LKQ": "LKQ Corporation",    "NOV": "NOV Inc",
    "RIG": "Transocean Ltd (Switzerland)",    "SGHC": "Super Group (SGHC) Limited",    "LAD": "Lithia Motors Inc",    "M": "Macy's Inc",
    "Z": "Zillow Group Inc. Class C Ca",    "CHRD": "Chord Energy Corporation",    "TMHC": "Taylor Morrison Home Corpora",    "ZG": "Zillow Group Inc",
    "BBUC": "Brookfield Business Corporat",    "RRR": "Red Rock Resorts Inc",    "GOLF": "Acushnet Holdings Corp",    "MBLY": "Mobileye Global Inc",
    "BYD": "Boyd Gaming Corporation",    "VSXY": "Victorias Secret & Co",    "GTX": "Garrett Motion Inc",    "COGT": "Cogent Biosciences Inc",
    "MSA": "MSA Safety Incorporated",    "CPA": "Copa Holdings S.A",    "GATX": "GATX Corporation",    "WH": "Wyndham Hotels & Resorts Inc",
    "SRRK": "Scholar Rock Holding Corpora",    "PACS": "PACS Group Inc",    "AN": "AutoNation Inc",    "CGON": "CG Oncology Inc. Common stoc",
    "INGM": "Ingram Micro Holding Corpora",    "SM": "SM Energy Company",    "MRCY": "Mercury Systems Inc",    "FND": "Floor & Decor Holdings Inc",
    "VSEC": "VSE Corporation",    "NE": "Noble Corporation plc A",    "MTDR": "Matador Resources Company",    "ENPH": "Enphase Energy Inc",
    "CZR": "Caesars Entertainment Inc",    "RGTI": "Rigetti Computing Inc",    "IBP": "Installed Building Products ",    "URBN": "Urban Outfitters Inc",
    "WFRD": "Weatherford International pl",    "BB": "BlackBerry Limited",    "PSMT": "PriceSmart Inc",    "TTAN": "ServiceTitan Inc",
    "TWST": "Twist Bioscience Corporation",    "CHE": "Chemed Corp",    "MATX": "Matson Inc",    "ALK": "Alaska Air Group Inc",
    "LGND": "Ligand Pharmaceuticals Incor",    "PAYC": "Paycom Software Inc",    "CROX": "Crocs Inc",    "RUSHB": "Rush Enterprises Inc",
    "GDS": "GDS Holdings Limited ADS",    "GXO": "GXO Logistics Inc",    "BZ": "KANZHUN LIMITED American Dep",    "CHDN": "Churchill Downs Incorporated",
    "DBX": "Dropbox Inc",    "SEI": "Solaris Energy Infrastructur",    "CAR": "Avis Budget Group Inc",    "HNGE": "Hinge Health Inc",
    "MMYT": "MakeMyTrip Limited",    "PCOR": "Procore Technologies Inc",    "SPHR": "Sphere Entertainment Co",    "GLBE": "Global-E Online Ltd",
    "RUSHA": "Rush Enterprises Inc. Cl A",    "DSGX": "Descartes Systems Group Inc.",    "BLCO": "Bausch + Lomb Corporation Co",    "TFX": "Teleflex Incorporated",
    "DUOL": "Duolingo Inc",    "ESTC": "Elastic N.V",    "STVN": "Stevanato Group S.p.A",    "MTH": "Meritage Homes Corporation",
    "ACLS": "Axcelis Technologies Inc",    "REYN": "Reynolds Consumer Products I",    "AMRX": "Amneal Pharmaceuticals Inc",    "CVLT": "Commvault Systems Inc",
    "GNTX": "Gentex Corporation",    "TEO": "Telecom Argentina SA",    "NAVN": "Navan Inc",    "TVTX": "Travere Therapeutics Inc",
    "XENE": "Xenon Pharmaceuticals Inc. C",    "UCTT": "Ultra Clean Holdings Inc",    "OMAB": "Grupo Aeroportuario del Cent",    "DOX": "Amdocs Limited",
    "PCTY": "Paylocity Holding Corporatio",    "SON": "Sonoco Products Company",    "OTEX": "Open Text Corporation Common",    "VAL": "Valaris Limited Common Share",
    "LYFT": "Lyft Inc",    "BOOT": "Boot Barn Holdings Inc",    "TKC": "Turkcell Iletisim Hizmetleri",    "MARA": "MARA Holdings Inc",
    "CAI": "Caris Life Sciences Inc",    "DIOD": "Diodes Incorporated",    "ORKA": "Oruka Therapeutics Inc",    "FTDR": "Frontdoor Inc",
    "CRSP": "CRISPR Therapeutics AG Commo",    "BLLN": "BillionToOne Inc",    "INDV": "Indivior Pharmaceuticals Inc",    "PATH": "UiPath Inc",
    "S": "SentinelOne Inc",    "APPF": "AppFolio Inc",    "SITE": "SiteOne Landscape Supply Inc",    "GLNG": "Golar Lng Ltd",
    "MUR": "Murphy Oil Corporation",    "CHH": "Choice Hotels International ",    "PSN": "Parsons Corporation",    "MGY": "Magnolia Oil & Gas Corporati",
    "DNTH": "Dianthus Therapeutics Inc",    "PBF": "PBF Energy Inc",    "MDA": "MDA Space Ltd. Common Shares",    "MANE": "Veradermics Incorporated",
    "ADT": "ADT Inc",    "EQPT": "EquipmentShare.com Inc",    "AMTM": "Amentum Holdings Inc",    "GBTG": "Global Business Travel Group",
    "DFTX": "Definium Therapeutics Inc. C",    "SHC": "Sotera Health Company",    "XMTR": "Xometry Inc",    "IEP": "Icahn Enterprises L.P",
    "HESM": "Hess Midstream LP Representi",    "SYNA": "Synaptics Incorporated $0.00",    "FELE": "Franklin Electric Co. Inc",    "PEGA": "Pegasystems Inc",
    "CRC": "California Resources Corpora",    "SKY": "Champion Homes Inc",    "TNL": "Travel   Leisure Co. Common ",    "CNX": "CNX Resources Corporation",
    "MTN": "Vail Resorts Inc",    "UNF": "Unifirst Corporation",    "ACIW": "ACI Worldwide Inc",    "POWI": "Power Integrations Inc",
    "RDNT": "RadNet Inc",    "ALHC": "Alignment Healthcare Inc",    "LB": "LandBridge Company LLC Share",    "G": "Genpact Limited",
    "CVCO": "Cavco Industries Inc. When I",    "IPGP": "IPG Photonics Corporation",    "CELC": "Celcuity Inc",    "VCYT": "Veracyte Inc",
    "ERAS": "Erasca Inc",    "GTLB": "GitLab Inc",    "WEX": "WEX Inc. common stock",    "VECO": "Veeco Instruments Inc",
    "CMBT": "CMB.TECH NV",    "LION": "Lionsgate Studios Corp Commo",    "DOO": "BRP Inc. Common Subordinate ",    "RELY": "Remitly Global Inc",
    "HRB": "H&R Block Inc",    "AXTI": "AXT Inc",    "SAIC": "Science Applications Interna",    "SRAD": "Sportradar Group AG",
    "WING": "Wingstop Inc",    "LILAP": "Liberty Latin America Ltd. 9",    "EWTX": "Edgewise Therapeutics Inc",    "HCC": "Warrior Met Coal Inc",
    "ZETA": "Zeta Global Holdings Corp",    "LIVN": "LivaNova PLC",    "LBRT": "Liberty Energy Inc. common s",    "LFTO": "Liftoff Mobile Inc",
    "RXO": "RXO Inc",    "VRNS": "Varonis Systems Inc",    "ATMU": "Atmus Filtration Technologie",    "IRDM": "Iridium Communications Inc",
    "BBWI": "Bath & Body Works Inc",    "OCTV": "Octave Intelligence plc",    "KNSA": "Kiniksa Pharmaceuticals Inte",    "TNGX": "Tango Therapeutics Inc",
    "LBRDK": "Liberty Broadband Corporatio",    "LBRDA": "Liberty Broadband Corporatio",    "NVST": "Envista Holdings Corporation",    "LBTYB": "Liberty Global Ltd. Common S",
    "STUB": "StubHub Holdings Inc",    "OLLI": "Ollie's Bargain Outlet Holdi",    "HGV": "Hilton Grand Vacations Inc",    "VKTX": "Viking Therapeutics Inc",
    "TPC": "Tutor Perini Corporation",    "WHD": "Cactus Inc",    "CAAP": "Corporacion America Airports",    "BFH": "Bread Financial Holdings Inc",
    "TDS": "Telephone and Data Systems I",    "FCN": "FTI Consulting Inc",    "MMSI": "Merit Medical Systems Inc",    "BRC": "Brady Corporation",
    "OPLN": "OPENLANE Inc",    "KVYO": "Klaviyo Inc. Series A",    "NVTS": "Navitas Semiconductor Corpor",    "CNR": "Core Natural Resources Inc",
    "PLNT": "Planet Fitness Inc",    "PII": "Polaris Inc",    "QLYS": "Qualys Inc",    "OLED": "Universal Display Corporatio",
    "PI": "Impinj Inc",    "MHO": "M/I Homes Inc",    "CRK": "Comstock Resources Inc",    "ACAD": "ACADIA Pharmaceuticals Inc",
    "EXTR": "Extreme Networks Inc",    "EPAM": "EPAM Systems Inc",    "ANDG": "Andersen Group Inc",    "INSW": "International Seaways Inc",
    "ONDS": "Ondas Inc",    "DORM": "Dorman Products Inc",    "MAT": "Mattel Inc",    "MMED": "MiniMed Group Inc",
    "NTSK": "Netskope Inc",    "ANF": "Abercrombie & Fitch Company",    "LIF": "Life360 Inc",    "CAKE": "Cheesecake Factory Incorpora",
    "OII": "Oceaneering International In",    "DNLI": "Denali Therapeutics Inc",    "GEO": "Geo Group Inc (The) REIT",    "STNG": "Scorpio Tankers Inc. Common ",
    "SKYW": "SkyWest Inc",    "PHI": "PLDT Inc. Sponsored ADR",    "ELF": "e.l.f. Beauty Inc",    "PTRN": "Pattern Group Inc. Series A",
    "EXLS": "ExlService Holdings Inc",    "CHEF": "The Chefs' Warehouse Inc",    "CPRX": "Catalyst Pharmaceuticals Inc",    "LFST": "LifeStance Health Group Inc",
    "IRTC": "iRhythm Holdings Inc",    "VEON": "VEON Ltd. ADS",    "RCUS": "Arcus Biosciences Inc",    "KBH": "KB Home",
    "CON": "Concentra Group Holdings Par",    "YETI": "YETI Holdings Inc",    "ABG": "Asbury Automotive Group Inc",    "CNK": "Cinemark Holdings Inc Cinema",
    "LBTYA": "Liberty Global Ltd. Common S",    "WBI": "WaterBridge Infrastructure L",    "MSGE": "Madison Square Garden Entert",    "ICUI": "ICU Medical Inc",
    "NAMS": "NewAmsterdam Pharma Company ",    "PTEN": "Patterson-UTI Energy Inc",    "RGC": "Regencell Bioscience Holding",    "CRNX": "Crinetics Pharmaceuticals In",
    "BKD": "Brookdale Senior Living Inc",    "KFY": "Korn Ferry",    "XNDU": "Xanadu Quantum Technologies ",    "DLO": "DLocal Limited Common Shares",
    "WAY": "Waystar Holding Corp",    "HAFN": "Hafnia Limited Common Shares",    "DOCS": "Doximity Inc",    "OSIS": "OSI Systems Inc. (DE)",
    "LBTYK": "Liberty Global Ltd. Class C ",    "PLUG": "Plug Power Inc",    "GPI": "Group 1 Automotive Inc",    "AAP": "Advance Auto Parts Inc",
    "BATRA": "Atlanta Braves Holdings Inc.",    "OGN": "Organon & Co",    "HAE": "Haemonetics Corporation",    "LASR": "nLIGHT Inc",
    "BFAM": "Bright Horizons Family Solut",    "BEAM": "Beam Therapeutics Inc",    "BHE": "Benchmark Electronics Inc",    "FOUR": "Shift4 Payments Inc",
    "ZGN": "Ermenegildo Zegna N.V",    "HWKN": "Hawkins Inc",    "KYIV": "Kyivstar Group Ltd. Common S",    "BOX": "Box Inc",
    "GRBK": "Green Brick Partners Inc",    "NSIT": "Insight Enterprises Inc",    "RLAY": "Relay Therapeutics Inc",    "DYN": "Dyne Therapeutics Inc",
    "HP": "Helmerich & Payne Inc",    "PENG": "Penguin Solutions Inc",    "WRBY": "Warby Parker Inc",    "OPCH": "Option Care Health Inc",
    "CALY": "Callaway Golf Company",    "ADEA": "Adeia Inc",    "IPAR": "Interparfums Inc",    "ARQT": "Arcutis Biotherapeutics Inc",
    "CRGY": "Crescent Energy Company",    "BILL": "BILL Holdings Inc",    "ICHR": "Ichor Holdings",    "SIG": "Signet Jewelers Limited Comm",
    "TDW": "Tidewater Inc",    "COLM": "Columbia Sportswear Company",    "BATRK": "Atlanta Braves Holdings Inc.",    "ADPT": "Adaptive Biotechnologies Cor",
    "EROC": "ERock Inc",    "GPK": "Graphic Packaging Holding Co",    "ALMS": "Alumis Inc",    "IDYA": "IDEAYA Biosciences Inc",
    "ITGR": "Integer Holdings Corporation",    "SEDG": "SolarEdge Technologies Inc",    "CLBT": "Cellebrite DI Ltd",    "PPLI": "People Incorporated",
    "PHIN": "PHINIA Inc",    "PBLS": "Parabilis Medicines Inc",    "MNDY": "monday.com Ltd",    "ZIM": "ZIM Integrated Shipping Serv",
    "AD": "Array Digital Infrastructure",    "QURE": "uniQure N.V",    "PRVA": "Privia Health Group Inc",    "DAN": "Dana Incorporated",
    "RHI": "Robert Half Inc",    "PATK": "Patrick Industries Inc",    "SHOO": "Steven Madden Ltd",    "MGRC": "McGrath RentCorp",
    "TENB": "Tenable Holdings Inc",    "AEO": "American Eagle Outfitters In",    "RH": "RH",    "HTFL": "Heartflow Inc",
    "ASO": "Academy Sports and Outdoors ",    "ELVN": "Enliven Therapeutics Inc",    "PLBL": "Polibeli Group Ltd",    "CLMT": "Calumet Inc",
    "VC": "Visteon Corporation",    "BSM": "Black Stone Minerals L.P. Co",    "ASH": "Ashland Inc",    "PK": "Park Hotels & Resorts Inc",
    "TDC": "Teradata Corporation",    "BTE": "Baytex Energy Corp Common Sh",    "DHT": "DHT Holdings Inc",    "VERA": "Vera Therapeutics Inc",
    "RNG": "RingCentral Inc",    "NTCT": "NetScout Systems Inc",    "MGEE": "MGE Energy Inc",    "BWLP": "BW LPG Limited Common Shares",
    "MMS": "Maximus Inc",    "DK": "Delek US Holdings Inc",    "BTU": "Peabody Energy Corporation",    "RARE": "Ultragenyx Pharmaceutical In",
    "FA": "First Advantage Corporation",    "GPOR": "Gulfport Energy Corporation ",    "GRAL": "GRAIL Inc",    "CSAN": "Cosan S.A. ADS",
    "VISN": "Vistance Networks Inc",    "BKV": "BKV Corporation",    "SBLK": "Star Bulk Carriers Corp. Com",    "PENN": "PENN Entertainment Inc",
    "HNI": "HNI Corporation",    "EXPO": "Exponent Inc",    "AMBA": "Ambarella Inc",    "TRMD": "TORM plc",
    "BCC": "Boise Cascade L.L.C",    "CARG": "CarGurus Inc",    "INFQ": "Infleqtion Inc",    "CENT": "Central Garden & Pet Company",
    "TARS": "Tarsus Pharmaceuticals Inc",    "OSW": "OneSpaWorld Holdings Limited",    "IHS": "IHS Holding Limited",    "QTWO": "Q2 Holdings Inc",
    "AGYS": "Agilysys Inc. (DE)",    "CVI": "CVR Energy Inc",    "CLOV": "Clover Health Investments Co",    "PDFS": "PDF Solutions Inc",
    "CTOS": "Custom Truck One Source Inc",    "NESR": "National Energy Services Reu",    "RUM": "RUM Group Inc",    "PARR": "Par Pacific Holdings Inc",
    "SOUN": "SoundHound AI Inc",    "TMDX": "TransMedics Group Inc",    "HOG": "Harley-Davidson Inc",    "IRON": "Disc Medicine Inc",
    "KLRA": "Kailera Therapeutics Inc",    "CLDX": "Celldex Therapeutics Inc",    "PAY": "Paymentus Holdings Inc",    "WTTR": "Select Water Solutions Inc. ",
    "CCC": "CCC Intelligent Solutions Ho",    "ABM": "ABM Industries Incorporated",    "STNE": "StoneCo Ltd. Common Shares",    "ESTA": "Establishment Labs Holdings ",
    "SAH": "Sonic Automotive Inc",    "EROK": "EagleRock Land LLC shares re",    "DGII": "Digi International Inc",    "WK": "Workiva Inc",
    "SUPN": "Supernus Pharmaceuticals Inc",    "UAA": "Under Armour Inc",    "TRVI": "Trevi Therapeutics Inc",    "PAGS": "PagSeguro Digital Ltd. Commo",
    "NYAX": "Nayax Ltd",    "FSLY": "Fastly Inc",    "FRSH": "Freshworks Inc",    "BCRX": "BioCryst Pharmaceuticals Inc",
    "UA": "Under Armour Inc. Class C",    "BLBD": "Blue Bird Corporation",    "ATEN": "A10 Networks Inc",    "WOLF": "Wolfspeed Inc. New",
    "MGNI": "Magnite Inc",    "PTON": "Peloton Interactive Inc",    "DNOW": "DNOW Inc",    "WHR": "Whirlpool Corporation",
    "CENTA": "Central Garden & Pet Company",    "TNK": "Teekay Tankers Ltd",    "ASTH": "Astrana Health Inc",    "ACHC": "Acadia Healthcare Company In",
    "GRND": "Grindr Inc",    "SDRL": "Seadrill Limited Common Shar",    "BRZE": "Braze Inc",    "MBX": "MBX Biosciences Inc",
    "INOD": "Innodata Inc",    "KD": "Kyndryl Holdings Inc",    "IMAX": "Imax Corporation",    "AXGN": "Axogen Inc",
    "SHAK": "Shake Shack Inc",    "PAYO": "Payoneer Global Inc",    "NIQ": "NIQ Global Intelligence plc",    "SLBT": "SL Science Holding Limited",
    "WLY": "John Wiley & Sons Inc",    "LCII": "LCI Industries",    "NRIX": "Nurix Therapeutics Inc. Comm",    "PHVS": "Pharvaris N.V",
    "MCRI": "Monarch Casino & Resort Inc",    "NNNN": "Anbio Biotechnology",    "BHVN": "Biohaven Ltd. Common Shares",    "WLYB": "John Wiley & Sons Inc",
    "WIX": "Wix.com Ltd",    "FUN": "Six Flags Entertainment Corp",    "TALO": "Talos Energy Inc",    "AUPH": "Aurinia Pharmaceuticals Inc",
    "WU": "Western Union Company (The)",    "DAC": "Danaos Corporation",    "VVX": "V2X Inc",    "RAMP": "LiveRamp Holdings Inc",
    "CALX": "Calix Inc",    "NTLA": "Intellia Therapeutics Inc",    "PBH": "Prestige Consumer Healthcare",    "DRVN": "Driven Brands Holdings Inc",
    "JBLU": "JetBlue Airways Corporation",    "IMNM": "Immunome Inc",    "BKE": "Buckle Inc. (The)",    "AVPT": "AvePoint Inc",
    "VCEL": "Vericel Corporation",    "ALRM": "Alarm.com Holdings Inc",    "CMPR": "Cimpress plc (Ireland)",    "MLYS": "Mineralys Therapeutics Inc",
    "CPRI": "Capri Holdings Limited",    "TNET": "TriNet Group Inc",    "KSS": "Kohl's Corporation",    "SHO": "Sunstone Hotel Investors Inc",
    "XRAY": "DENTSPLY SIRONA Inc",    "AGIO": "Agios Pharmaceuticals Inc",    "LMAT": "LeMaitre Vascular Inc",    "PGNY": "Progyny Inc",
    "AMR": "Alpha Metallurgical Resource",    "OCUL": "Ocular Therapeutix Inc",    "KOD": "Kodiak Sciences Inc",    "AIN": "Albany International Corpora",
    "PLUS": "ePlus inc",    "BRUN": "Boost Run Inc",    "GENB": "Generate Biomedicines Inc",    "NKTR": "Nektar Therapeutics",
    "BFLY": "Butterfly Network Inc",    "NOG": "Northern Oil and Gas Inc",    "NEOG": "Neogen Corporation",    "TILE": "Interface Inc",
    "SEM": "Select Medical Holdings Corp",    "FLYW": "Flywire Corporation Voting",    "QUBT": "Quantum Computing Inc",    "EZPW": "EZCORP Inc. Non Voting",
    "SPSC": "SPS Commerce Inc",    "FBYD": "Falcon's Beyond Global Inc",    "WGS": "GeneDx Holdings Corp",    "ALGT": "Allegiant Travel Company",
    "ADMA": "ADMA Biologics Inc",    "ECO": "Okeanis Eco Tankers Corp",    "NUVB": "Nuvation Bio Inc",    "SGRY": "Surgery Partners Inc",
    "AIP": "Arteris Inc",    "TH": "Target Hospitality Corp",    "BRSL": "Brightstar Lottery PLC Tradi",    "CCS": "Century Communities Inc",
    "LPL": "LG Display Co Ltd AMERICAN D",    "MD": "Pediatrix Medical Group Inc",    "KARD": "Kardigan Inc",    "HRMY": "Harmony Biosciences Holdings",
    "BHC": "Bausch Health Companies Inc",    "PGEN": "Precigen Inc",    "BOBS": "Bob's Discount Furniture Inc",    "ABCL": "AbCellera Biologics Inc. Com",
    "SLS": "SELLAS Life Sciences Group I",    "UFPT": "UFP Technologies Inc",    "DJT": "Trump Media & Technology Gro",    "TGLS": "Tecnoglass Inc",
    "PVLA": "Palvella Therapeutics Inc",    "AMLX": "Amylyx Pharmaceuticals Inc",    "PLAB": "Photronics Inc",    "SION": "Sionna Therapeutics Inc",
    "HAWK": "HawkEye 360 Inc",    "AMSC": "American Superconductor Corp",    "EPAC": "Enerpac Tool Group Corp",    "CTS": "CTS Corporation",
    "PLSE": "Pulse Biosciences Inc (DE)",    "FLOC": "Flowco Holdings Inc",    "STOK": "Stoke Therapeutics Inc",    "XHR": "Xenia Hotels & Resorts Inc",
    "IOVA": "Iovance Biotherapeutics Inc",    "LIND": "Lindblad Expeditions Holding",    "ANIP": "ANI Pharmaceuticals Inc",    "RAPP": "Rapport Therapeutics Inc",
    "SNDA": "Sonida Senior Living Inc",    "FIGS": "FIGS Inc",    "ULCC": "Frontier Group Holdings Inc",    "GT": "The Goodyear Tire & Rubber C",
    "AVAH": "Aveanna Healthcare Holdings ",    "TYRA": "Tyra Biosciences Inc",    "CMPS": "COMPASS Pathways Plc America",    "GLUE": "Monte Rosa Therapeutics Inc",
    "VSTS": "Vestis Corporation",    "PUMP": "ProPetro Holding Corp",    "TIC": "TIC Solutions Inc",    "ADUS": "Addus HomeCare Corporation",
    "OMCL": "Omnicell Inc. ($0.001 par va",    "CNXN": "PC Connection Inc",    "VRDN": "Viridian Therapeutics Inc",    "AGL": "agilon health inc",
    "ZD": "Ziff Davis Inc",    "NEO": "NeoGenomics Inc",    "TSHA": "Taysha Gene Therapies Inc",    "AMBQ": "Ambiq Micro Inc",
    "VPG": "Vishay Precision Group Inc",    "CMRE": "Costamare Inc. $0.0001 par v",    "RXRX": "Recursion Pharmaceuticals In",    "CAPR": "Capricor Therapeutics Inc",
    "INVX": "Innovex International Inc",    "SNDX": "Syndax Pharmaceuticals Inc",    "VERX": "Vertex Inc",    "MH": "McGraw Hill Inc",
    "NVCR": "NovoCure Limited",    "PRG": "PROG Holdings Inc",    "GHRS": "GH Research PLC",    "ANAB": "AnaptysBio Inc",
    "ZYME": "Zymeworks Inc",    "BCAX": "Bicara Therapeutics Inc",    "INVA": "Innoviva Inc",    "AKTS": "Aktis Oncology Inc. Common s",
    "ARCO": "Arcos Dorados Holdings Inc. ",    "SKYT": "SkyWater Technology Inc",    "WLFC": "Willis Lease Finance Corpora",    "INTA": "Intapp Inc",
    "ALKT": "Alkami Technology Inc",    "SRPT": "Sarepta Therapeutics Inc. (D",    "ATAI": "AtaiBeckley Inc",    "STGW": "Stagwell Inc",
    "FTRE": "Fortrea Holdings Inc",    "BAND": "Bandwidth Inc",    "URGN": "UroGen Pharma Ltd",    "MQ": "Marqeta Inc",
    "VIR": "Vir Biotechnology Inc",    "COTY": "Coty Inc",    "SHLS": "Shoals Technologies Group In",    "WKC": "World Kinect Corporation",
    "PRCH": "Porch Group Inc",    "TRLV": "Trulieve Cannabis Corp. Subo",    "BBAI": "BigBear.ai Inc",    "HLMN": "Hillman Solutions Corp",
    "CBZ": "CBIZ Inc",    "RVLV": "Revolve Group Inc",    "LZB": "La-Z-Boy Incorporated",    "UZD": "Array Digital Infrastructure",
    "TPB": "Turning Point Brands Inc",    "HCSG": "Healthcare Services Group In",    "FLNG": "FLEX LNG Ltd",    "EVTC": "Evertec Inc",
    "HLIT": "Harmonic Inc",    "SVV": "Savers Value Village Inc",    "ABSI": "Absci Corporation",    "AAPG": "Ascentage Pharma Group Inter",
    "ADNT": "Adient plc",    "CRI": "Carter's Inc",    "RXT": "Rackspace Technology Inc",    "XPRO": "Expro Group Holdings N.V",
    "LEG": "Leggett & Platt Incorporated",    "LPG": "Dorian LPG Ltd",    "MRVI": "Maravai LifeSciences Holding",    "AVBP": "ArriVent BioPharma Inc",
    "MAN": "ManpowerGroup",    "NCNO": "nCino Inc",    "ZBIO": "Zenas BioPharma Inc",    "SEPN": "Septerna Inc",
    "BL": "BlackLine Inc",    "STAA": "STAAR Surgical Company",    "SFL": "SFL Corporation Ltd",    "LILA": "Liberty Latin America Ltd",
    "POET": "POET Technologies Inc. Commo",    "HROW": "Harrow Inc",    "EVCM": "EverCommerce Inc",    "DFH": "Dream Finders Homes Inc",
    "WINA": "Winmark Corporation",    "LILAK": "Liberty Latin America Ltd. C",    "DV": "DoubleVerify Holdings Inc",    "ATEX": "Anterix Inc",
    "KARO": "Karooooo Ltd",    "APPN": "Appian Corporation",    "AMC": "AMC Entertainment Holdings I",    "REAL": "The RealReal Inc",
    "ARDX": "Ardelyx Inc",    "MAZE": "Maze Therapeutics Inc",    "HURN": "Huron Consulting Group Inc",    "FIVN": "Five9 Inc",
    "WBTN": "WEBTOON Entertainment Inc. C",    "TRIP": "TripAdvisor Inc",    "UZE": "Array Digital Infrastructure",    "PRSU": "Pursuit Attractions and Hosp",
    "ASAN": "Asana Inc",    "MLTX": "MoonLake Immunotherapeutics",    "AMRC": "Ameresco Inc",    "NSP": "Insperity Inc",
    "ODC": "Oil-Dri Corporation Of Ameri",    "LGIH": "LGI Homes Inc",    "UZF": "Array Digital Infrastructure",    "MPLT": "MapLight Therapeutics Inc",
    "CSWC": "Capital Southwest Corporatio",    "EYE": "National Vision Holdings Inc",    "VET": "Vermilion Energy Inc. Common",    "OI": "O-I Glass Inc",
    "CDNA": "CareDx Inc",    "TDOC": "Teladoc Health Inc",    "ATRC": "AtriCure Inc",    "GIII": "G-III Apparel Group LTD",
    "IART": "Integra LifeSciences Holding",    "NVAX": "Novavax Inc",    "INNV": "InnovAge Holding Corp",    "GENI": "Genius Sports Limited",
    "INBX": "Inhibrx Biosciences Inc",    "WEN": "Wendy's Company (The)",    "WWW": "Wolverine World Wide Inc",    "IDT": "IDT Corporation",
    "DMRA": "Damora Therapeutics Inc",    "TTI": "Tetra Technologies Inc",    "OLPX": "Olaplex Holdings Inc",    "DCH": "Dauch Corporation",
    "CNXC": "Concentrix Corporation",    "PLTK": "Playtika Holding Corp",    "GSL": "Global Ship Lease Inc New Co",    "AOSL": "Alpha and Omega Semiconducto",
    "AHCO": "AdaptHealth Corp",    "DXC": "DXC Technology Company",    "ATEC": "Alphatec Holdings Inc",    "SHAZ": "SharonAI Holdings Inc",
    "SBH": "Sally Beauty Holdings Inc. (",    "BORR": "Borr Drilling Limited Common",    "BLFS": "BioLife Solutions Inc",    "NVGS": "Navigator Holdings Ltd. (Mar",
    "NBR": "Nabors Industries Ltd",    "ARDT": "Ardent Health Inc",    "PRGO": "Perrigo Company plc",    "BV": "BrightView Holdings Inc",
    "LSPD": "Lightspeed Commerce Inc. Sub",    "NSSC": "NAPCO Security Technologies ",    "HQ": "Horizon Quantum Holdings Ltd",    "FCEL": "FuelCell Energy Inc",
    "NAT": "Nordic American Tankers Limi",    "NRP": "Natural Resource Partners LP",    "MLKN": "MillerKnoll Inc",    "PSNL": "Personalis Inc",
    "KMTS": "Kestra Medical Technologies ",    "RES": "RPC Inc",    "NPKI": "NPK International Inc",    "COAG": "Hemab Therapeutics Holdings ",
    "UHAL": "U-Haul Holding Company",    "KOS": "Kosmos Energy Ltd. Common Sh",    "PAHC": "Phibro Animal Health Corpora",    "HLX": "Helix Energy Solutions Group",
    "AVLN": "Avalyn Pharma Inc",    "XERS": "Xeris Biopharma Holdings Inc",    "IMTX": "Immatics N.V",    "AI": "C3.ai Inc",
    "AEVA": "Aeva Technologies Inc",    "ENOV": "Enovis Corporation",    "CLVT": "Clarivate Plc",    "DSGR": "Distribution Solutions Group",
    "YELP": "Yelp Inc",    "SCL": "Stepan Company",    "PRGS": "Progress Software Corporatio",    "AMN": "AMN Healthcare Services Inc",
    "INSP": "Inspire Medical Systems Inc",    "VIA": "Via Transportation Inc",    "PNTG": "The Pennant Group Inc",    "HLF": "Herbalife Ltd. Common Shares",
    "ITRN": "Ituran Location and Control ",    "SVRA": "Savara Inc",    "MBC": "MasterBrand Inc",    "VTOL": "Bristow Group Inc",
    "CCEC": "Capital Clean Energy Carrier",    "PRCT": "PROCEPT BioRobotics Corporat",    "CEVA": "CEVA Inc",    "CCO": "Clear Channel Outdoor Holdin",
    "BLKB": "Blackbaud Inc",    "TBLA": "Taboola.com Ltd",    "MNKD": "MannKind Corporation",    "SDGR": "Schrodinger Inc",
    "CDRE": "Cadre Holdings Inc",    "IRMD": "iRadimed Corporation",    "GLOB": "Globant S.A. Common Shares",    "HBNB": "Hotel101 Global Holdings Cor",
    "WLDN": "Willdan Group Inc",    "RDWR": "Radware Ltd",    "PZZA": "Papa John's International In",    "LQDT": "Liquidity Services Inc",
    "BJRI": "BJ's Restaurants Inc",    "ARRY": "Array Technologies Inc",    "ICFI": "ICF International Inc",    "EPC": "Edgewell Personal Care Compa",
    "SOC": "Sable Offshore Corp",    "GCT": "GigaCloud Technology Inc",    "AVNS": "Avanos Medical Inc",    "TDAY": "USA TODAY Co. Inc",
    "BRAI": "Braiin Limited",    "UPBD": "Upbound Group Inc",    "SPH": "Suburban Propane Partners L.",    "CXM": "Sprinklr Inc",
    "ACVA": "ACV Auctions Inc",    "ARHS": "Arhaus Inc",    "OPK": "OPKO Health Inc",    "CGEM": "Cullinan Therapeutics Inc",
    "AZTA": "Azenta Inc",    "TEN": "Tsakos Energy Navigation Ltd",    "COLL": "Collegium Pharmaceutical Inc",    "AIAI": "AIAI Holdings Corporation",
    "OMDA": "Omada Health Inc",    "THRM": "Gentherm Inc",    "WVE": "Wave Life Sciences Ltd",    "AORT": "Artivion Inc",
    "ENHA": "Enhanced Group Inc",    "CRVS": "Corvus Pharmaceuticals Inc",    "RCAT": "Red Cat Holdings Inc",    "MGRT": "Mega Fortune Company Limited",
    "XNCR": "Xencor Inc",    "BLDP": "Ballard Power Systems Inc. C",    "ALVO": "Alvotech",    "CBRL": "Cracker Barrel Old Country S",
    "TNDM": "Tandem Diabetes Care Inc",    "JBIO": "Jade Biosciences Inc",    "CSIQ": "Canadian Solar Inc. Common S",    "ACEL": "Accel Entertainment Inc",
    "MGTX": "MeiraGTx Holdings plc",    "DLX": "Deluxe Corporation",    "SG": "Sweetgreen Inc",    "TRUP": "Trupanion Inc",
    "LUCK": "Lucky Strike Entertainment C",    "AIIR": "Air Global PLC",    "CNMD": "CONMED Corporation",    "SPTX": "Seaport Therapeutics Inc",
    "ACDC": "ProFrac Holding Corp",    "CRON": "Cronos Group Inc. Common Sha",    "SCSC": "ScanSource Inc",    "NUTX": "Nutex Health Inc",
    "KDK": "Kodiak AI Inc",    "PDS": "Precision Drilling Corporati",    "GNK": "Genco Shipping & Trading Lim",    "LXRX": "Lexicon Pharmaceuticals Inc",
    "LMRI": "Lumexa Imaging Holdings Inc",    "USPH": "U.S. Physical Therapy Inc",    "RZLV": "Rezolve AI PLC",    "BIOA": "BioAge Labs Inc",

}
